gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Emerald Battle Revolution!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This game focuses on expanding the\n"
	.string "Battle Frontier, and aims to make\l"
	.string "building teams as easy as possible.\p"
	.string "You can find everything you need\n"
	.string "in the Battle Frontier Underground,\l"
	.string "or even buy a ready-made team!\p"
	.string "Opponents you face will have randomly\n"
	.string "generated teams, which will get\l"
	.string "stronger the more wins you have.\p"
	.string "You have full control over the\n"
	.string "music, battle rules, and more!\p"
	.string "But, that's enough about that!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Who are you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who is here to test your\n"
	.string "skills at the Battle Frontier.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "You will be given some money, key\n"
	.string "items and POKéMON to get started.\l"
	.string "What you do after that is up to you!\p"
	.string "$"
