gText_Birch_Welcome::
	.string "Welcome to Emerald Battle Revolution!\p"
	.string "This game focuses on expanding the\n"
	.string "Battle Frontier, and aims to make\l"
	.string "building teams as easy as possible.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "You can build your own POKéMON teams\n"
	.string "in the Battle Frontier Underground,\l"
	.string "or even buy a ready-made team!\p"
	.string "Opponents you face will have randomly\n"
	.string "generated teams, which will get\l"
	.string "stronger the more you win!\p"
	.string "The rest of Hoenn is still available\n"
	.string "to explore, too.\p"
	.string "But, that's enough about that!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Who are you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who is here to\n"
	.string "challenge the Battle Frontier.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and hard battles await!\p"
	.string "$"
