# 1 "data/maps/BattleFrontier_Underground_B2F_PokeCenter_2F/scripts.pory"

# 2 "data/maps/BattleFrontier_Underground_B2F_PokeCenter_2F/scripts.pory"
BattleFrontier_Underground_B2F_PokeCenter_2F_MapScripts::
# 3 "data/maps/BattleFrontier_Underground_B2F_PokeCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CableClub_OnFrame
# 4 "data/maps/BattleFrontier_Underground_B2F_PokeCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, CableClub_OnWarp
# 5 "data/maps/BattleFrontier_Underground_B2F_PokeCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, CableClub_OnLoad
# 6 "data/maps/BattleFrontier_Underground_B2F_PokeCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CableClub_OnTransition
# 7 "data/maps/BattleFrontier_Underground_B2F_PokeCenter_2F/scripts.pory"
	.byte 0
