#ifndef GUARD_CONFIG_PRICES_H
#define GUARD_CONFIG_PRICES_H

// Poke-Balls
#define IP_PRICE_BALL 1000
#define IP_PRICE_SPECIAL_BALL 10000

// Training Items
#define IP_PRICE_MINT 500
#define IP_PRICE_DRUG 500
#define IP_PRICE_CANDY 20
#define IP_PRICE_FEATHER 50
#define IP_PRICE_ABILITY 1000
#define IP_PRICE_BOTTLE_CAP 1000

// Held Items
#define IP_PRICE_BERRY 50
#define IP_PRICE_Z_CRYSTAL 1000
#define IP_PRICE_HELD_ITEM 1000
#define IP_PRICE_FORME_ITEM 2000

// TMs & HMs
#define IP_PRICE_TM 1000
#define IP_PRICE_HM 2000

// Other Items
#define IP_PRICE_FOSSIL 2000
#define IP_PRICE_KEY_ITEM 1000
#define IP_PRICE_EVO_STONE 1000
#define IP_PRICE_TERA_SHARD 1000

#endif // GUARD_CONFIG_ITEM_H
