Auto_EventScript_Sample_Sets_Controls::
# 5 "data/scripts/sample_sets_options.pory"
	msgbox Auto_EventScript_Sample_Sets_Controls_Text_0
# 6 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page1
	return


Auto_EventScript_Sample_Sets_Page1::
# 11 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page1
# 12 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 14 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page1_2
# 16 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page1_3
# 18 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page1_4
# 20 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page1_5
# 22 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page1_6
# 24 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page1_7
# 26 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page1_8
# 29 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page1_2:
# 15 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Aegislash_Page1
	return

Auto_EventScript_Sample_Sets_Page1_3:
# 17 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Amoonguss_Page1
	return

Auto_EventScript_Sample_Sets_Page1_4:
# 19 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Arcanine_Page1
	return

Auto_EventScript_Sample_Sets_Page1_5:
# 21 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Archaludon_Page1
	return

Auto_EventScript_Sample_Sets_Page1_6:
# 23 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Basculegion_Page1
	return

Auto_EventScript_Sample_Sets_Page1_7:
# 25 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page12
	return

Auto_EventScript_Sample_Sets_Page1_8:
# 27 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page2
	return


Auto_EventScript_Sample_Sets_Page2::
# 35 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page2
# 36 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 38 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page2_2
# 40 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page2_3
# 42 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page2_4
# 44 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page2_5
# 46 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page2_6
# 48 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page2_7
# 50 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page2_8
# 53 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page2_2:
# 39 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Calyrex_Page1
	return

Auto_EventScript_Sample_Sets_Page2_3:
# 41 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Charizard_Page1
	return

Auto_EventScript_Sample_Sets_Page2_4:
# 43 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Chi_Yu_Page1
	return

Auto_EventScript_Sample_Sets_Page2_5:
# 45 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Chien_Pao_Page1
	return

Auto_EventScript_Sample_Sets_Page2_6:
# 47 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Cresselia_Page1
	return

Auto_EventScript_Sample_Sets_Page2_7:
# 49 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page1
	return

Auto_EventScript_Sample_Sets_Page2_8:
# 51 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page3
	return


Auto_EventScript_Sample_Sets_Page3::
# 59 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page3
# 60 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 62 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page3_2
# 64 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page3_3
# 66 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page3_4
# 68 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page3_5
# 70 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page3_6
# 72 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page3_7
# 74 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page3_8
# 77 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page3_2:
# 63 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Farigiraf_Page1
	return

Auto_EventScript_Sample_Sets_Page3_3:
# 65 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Flutter_Mane_Page1
	return

Auto_EventScript_Sample_Sets_Page3_4:
# 67 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Gardevoir_Page1
	return

Auto_EventScript_Sample_Sets_Page3_5:
# 69 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Garganacl_Page1
	return

Auto_EventScript_Sample_Sets_Page3_6:
# 71 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Gengar_Page1
	return

Auto_EventScript_Sample_Sets_Page3_7:
# 73 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page2
	return

Auto_EventScript_Sample_Sets_Page3_8:
# 75 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page4
	return


Auto_EventScript_Sample_Sets_Page4::
# 83 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page4
# 84 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 86 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page4_2
# 88 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page4_3
# 90 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page4_4
# 92 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page4_5
# 94 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page4_6
# 96 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page4_7
# 98 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page4_8
# 101 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page4_2:
# 87 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Gholdengo_Page1
	return

Auto_EventScript_Sample_Sets_Page4_3:
# 89 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Groudon_Page1
	return

Auto_EventScript_Sample_Sets_Page4_4:
# 91 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Hatterene_Page1
	return

Auto_EventScript_Sample_Sets_Page4_5:
# 93 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Heatran_Page1
	return

Auto_EventScript_Sample_Sets_Page4_6:
# 95 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Incineroar_Page1
	return

Auto_EventScript_Sample_Sets_Page4_7:
# 97 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page3
	return

Auto_EventScript_Sample_Sets_Page4_8:
# 99 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page5
	return


Auto_EventScript_Sample_Sets_Page5::
# 107 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page5
# 108 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 110 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page5_2
# 112 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page5_3
# 114 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page5_4
# 116 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page5_5
# 118 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page5_6
# 120 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page5_7
# 122 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page5_8
# 125 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page5_2:
# 111 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Indeedee_F_Page1
	return

Auto_EventScript_Sample_Sets_Page5_3:
# 113 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Iron_Bundle_Page1
	return

Auto_EventScript_Sample_Sets_Page5_4:
# 115 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Iron_Hands_Page1
	return

Auto_EventScript_Sample_Sets_Page5_5:
# 117 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kangaskhan_Page1
	return

Auto_EventScript_Sample_Sets_Page5_6:
# 119 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kartana_Page1
	return

Auto_EventScript_Sample_Sets_Page5_7:
# 121 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page4
	return

Auto_EventScript_Sample_Sets_Page5_8:
# 123 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page6
	return


Auto_EventScript_Sample_Sets_Page6::
# 131 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page6
# 132 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 134 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page6_2
# 136 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page6_3
# 138 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page6_4
# 140 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page6_5
# 142 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page6_6
# 144 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page6_7
# 146 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page6_8
# 149 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page6_2:
# 135 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kingambit_Page1
	return

Auto_EventScript_Sample_Sets_Page6_3:
# 137 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Koraidon_Page1
	return

Auto_EventScript_Sample_Sets_Page6_4:
# 139 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kyogre_Page1
	return

Auto_EventScript_Sample_Sets_Page6_5:
# 141 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Lando_T_Page1
	return

Auto_EventScript_Sample_Sets_Page6_6:
# 143 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Landorus_Page1
	return

Auto_EventScript_Sample_Sets_Page6_7:
# 145 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page5
	return

Auto_EventScript_Sample_Sets_Page6_8:
# 147 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page7
	return


Auto_EventScript_Sample_Sets_Page7::
# 155 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page7
# 156 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 158 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page7_2
# 160 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page7_3
# 162 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page7_4
# 164 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page7_5
# 166 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page7_6
# 168 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page7_7
# 170 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page7_8
# 173 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page7_2:
# 159 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Latias_Page1
	return

Auto_EventScript_Sample_Sets_Page7_3:
# 161 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Lunala_Page1
	return

Auto_EventScript_Sample_Sets_Page7_4:
# 163 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Manectric_Page1
	return

Auto_EventScript_Sample_Sets_Page7_5:
# 165 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Mawile_Page1
	return

Auto_EventScript_Sample_Sets_Page7_6:
# 167 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Metagross_Page1
	return

Auto_EventScript_Sample_Sets_Page7_7:
# 169 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page6
	return

Auto_EventScript_Sample_Sets_Page7_8:
# 171 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page8
	return


Auto_EventScript_Sample_Sets_Page8::
# 179 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page8
# 180 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 182 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page8_2
# 184 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page8_3
# 186 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page8_4
# 188 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page8_5
# 190 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page8_6
# 192 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page8_7
# 194 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page8_8
# 197 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page8_2:
# 183 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Miraidon_Page1
	return

Auto_EventScript_Sample_Sets_Page8_3:
# 185 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1
	return

Auto_EventScript_Sample_Sets_Page8_4:
# 187 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1
	return

Auto_EventScript_Sample_Sets_Page8_5:
# 189 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1
	return

Auto_EventScript_Sample_Sets_Page8_6:
# 191 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Pelipper_Page1
	return

Auto_EventScript_Sample_Sets_Page8_7:
# 193 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page7
	return

Auto_EventScript_Sample_Sets_Page8_8:
# 195 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page9
	return


Auto_EventScript_Sample_Sets_Page9::
# 203 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page9
# 204 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 206 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page9_2
# 208 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page9_3
# 210 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page9_4
# 212 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page9_5
# 214 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page9_6
# 216 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page9_7
# 218 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page9_8
# 221 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page9_2:
# 207 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Politoed_Page1
	return

Auto_EventScript_Sample_Sets_Page9_3:
# 209 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Porygon2_Page1
	return

Auto_EventScript_Sample_Sets_Page9_4:
# 211 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Raging_Bolt_Page1
	return

Auto_EventScript_Sample_Sets_Page9_5:
# 213 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Regidrago_Page1
	return

Auto_EventScript_Sample_Sets_Page9_6:
# 215 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Rillaboom_Page1
	return

Auto_EventScript_Sample_Sets_Page9_7:
# 217 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page8
	return

Auto_EventScript_Sample_Sets_Page9_8:
# 219 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page10
	return


Auto_EventScript_Sample_Sets_Page10::
# 227 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page10
# 228 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 230 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page10_2
# 232 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page10_3
# 234 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page10_4
# 236 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page10_5
# 238 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page10_6
# 240 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page10_7
# 242 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page10_8
# 245 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page10_2:
# 231 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Roaring_Moon_Page1
	return

Auto_EventScript_Sample_Sets_Page10_3:
# 233 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Salamence_Page1
	return

Auto_EventScript_Sample_Sets_Page10_4:
# 235 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Talonflame_Page1
	return

Auto_EventScript_Sample_Sets_Page10_5:
# 237 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ting_Lu_Page1
	return

Auto_EventScript_Sample_Sets_Page10_6:
# 239 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Tinkaton_Page1
	return

Auto_EventScript_Sample_Sets_Page10_7:
# 241 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page9
	return

Auto_EventScript_Sample_Sets_Page10_8:
# 243 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page11
	return


Auto_EventScript_Sample_Sets_Page11::
# 251 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page11
# 252 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 254 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page11_2
# 256 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page11_3
# 258 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page11_4
# 260 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page11_5
# 262 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page11_6
# 264 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page11_7
# 266 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page11_8
# 269 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page11_2:
# 255 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Torkoal_Page1
	return

Auto_EventScript_Sample_Sets_Page11_3:
# 257 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Tornadus_Page1
	return

Auto_EventScript_Sample_Sets_Page11_4:
# 259 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Tyranitar_Page1
	return

Auto_EventScript_Sample_Sets_Page11_5:
# 261 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ursaluna_Page1
	return

Auto_EventScript_Sample_Sets_Page11_6:
# 263 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1
	return

Auto_EventScript_Sample_Sets_Page11_7:
# 265 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page10
	return

Auto_EventScript_Sample_Sets_Page11_8:
# 267 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page12
	return


Auto_EventScript_Sample_Sets_Page12::
# 275 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Page12
# 276 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 278 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Page12_2
# 280 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Page12_3
# 282 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Page12_4
# 284 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Page12_5
# 286 "data/scripts/sample_sets_options.pory"
	case 4, Auto_EventScript_Sample_Sets_Page12_6
# 288 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Page12_7
# 290 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Page12_8
# 293 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_End
	return

Auto_EventScript_Sample_Sets_Page12_2:
# 279 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1
	return

Auto_EventScript_Sample_Sets_Page12_3:
# 281 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1
	return

Auto_EventScript_Sample_Sets_Page12_4:
# 283 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Xerneas_Page1
	return

Auto_EventScript_Sample_Sets_Page12_5:
# 285 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Zacian_Page1
	return

Auto_EventScript_Sample_Sets_Page12_6:
# 287 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Zamazenta_Page1
	return

Auto_EventScript_Sample_Sets_Page12_7:
# 289 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page11
	return

Auto_EventScript_Sample_Sets_Page12_8:
# 291 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page1
	return


Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1::
# 299 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Urshifu_Rs_Page1
# 300 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 302 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_2
# 305 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_3
# 308 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_4
# 311 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_5
# 313 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_6
# 316 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page12
	return

Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_2:
# 303 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSHIFU_RAPID_STRIKE, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 1, 0, 252, 0, 252, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_AQUA_JET, MOVE_CLOSE_COMBAT, MOVE_SURGING_STRIKES, FALSE, FALSE, TYPE_WATER
# 304 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_3:
# 306 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSHIFU_RAPID_STRIKE, 65, ITEM_MYSTIC_WATER, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 1, 12, 156, 4, 252, 0, 84, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_AQUA_JET, MOVE_CLOSE_COMBAT, MOVE_SURGING_STRIKES, FALSE, FALSE, TYPE_WATER
# 307 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_4:
# 309 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSHIFU_RAPID_STRIKE, 65, ITEM_CHOICE_SCARF, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 12, 156, 4, 252, 0, 84, 31, 31, 31, 31, 31, 31, MOVE_U_TURN, MOVE_AQUA_JET, MOVE_CLOSE_COMBAT, MOVE_SURGING_STRIKES, FALSE, FALSE, TYPE_WATER
# 310 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_5:
# 312 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1
	return

Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1_6:
# 314 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Urshifu_Rs_Page1
	return


Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1::
# 322 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Urshifu_Ss_Page1
# 323 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 325 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1_2
# 328 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1_3
# 331 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1_4
# 333 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1_5
# 336 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page12
	return

Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1_2:
# 326 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSHIFU, 65, ITEM_CHOICE_BAND, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 1, 0, 236, 0, 252, 0, 20, 31, 31, 31, 31, 31, 31, MOVE_U_TURN, MOVE_WICKED_BLOW, MOVE_CLOSE_COMBAT, MOVE_SUCKER_PUNCH, FALSE, FALSE, TYPE_DARK
# 327 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1_3:
# 329 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSHIFU, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 0, 252, 0, 252, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_WICKED_BLOW, MOVE_CLOSE_COMBAT, MOVE_SUCKER_PUNCH, FALSE, FALSE, TYPE_GHOST
# 330 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1_4:
# 332 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1
	return

Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1_5:
# 334 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Urshifu_Ss_Page1
	return


Auto_EventScript_Sample_Sets_Xerneas_Page1::
# 342 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Xerneas_Page1
# 343 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 345 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Xerneas_Page1_2
# 348 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Xerneas_Page1_3
# 351 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Xerneas_Page1_4
# 353 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Xerneas_Page1_5
# 356 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page12
	return

Auto_EventScript_Sample_Sets_Xerneas_Page1_2:
# 346 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_XERNEAS, 65, ITEM_POWER_HERB, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 4, 0, 4, 252, 244, 4, 31, 0, 31, 31, 31, 31, MOVE_MOONBLAST, MOVE_DAZZLING_GLEAM, MOVE_GEOMANCY, MOVE_PROTECT, FALSE, FALSE, FALSE
# 347 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Xerneas_Page1_3:
# 349 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_XERNEAS, 65, ITEM_POWER_HERB, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 44, 0, 20, 252, 188, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_GEOMANCY, MOVE_DAZZLING_GLEAM, MOVE_MOONBLAST, FALSE, FALSE, FALSE
# 350 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Xerneas_Page1_4:
# 352 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Xerneas_Page1
	return

Auto_EventScript_Sample_Sets_Xerneas_Page1_5:
# 354 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Xerneas_Page1
	return


Auto_EventScript_Sample_Sets_Zacian_Page1::
# 362 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Zacian_Page1
# 363 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 365 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Zacian_Page1_2
# 368 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Zacian_Page1_3
# 371 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Zacian_Page1_4
# 373 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Zacian_Page1_5
# 376 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page12
	return

Auto_EventScript_Sample_Sets_Zacian_Page1_2:
# 366 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_ZACIAN, 65, ITEM_RUSTED_SWORD, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 252, 76, 4, 164, 0, 12, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_BEHEMOTH_BLADE, MOVE_PLAY_ROUGH, MOVE_TERA_BLAST, FALSE, FALSE, TYPE_GROUND
# 367 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Zacian_Page1_3:
# 369 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_ZACIAN, 65, ITEM_RUSTED_SWORD, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 252, 76, 4, 164, 0, 12, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_IRON_HEAD, MOVE_SACRED_SWORD, MOVE_PLAY_ROUGH, FALSE, FALSE, TYPE_STELLAR
# 370 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Zacian_Page1_4:
# 372 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Zacian_Page1
	return

Auto_EventScript_Sample_Sets_Zacian_Page1_5:
# 374 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Zacian_Page1
	return


Auto_EventScript_Sample_Sets_Zamazenta_Page1::
# 382 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Zamazenta_Page1
# 383 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 385 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Zamazenta_Page1_2
# 388 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Zamazenta_Page1_3
# 390 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Zamazenta_Page1_4
# 393 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page12
	return

Auto_EventScript_Sample_Sets_Zamazenta_Page1_2:
# 386 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_ZAMAZENTA, 65, ITEM_RUSTED_SHIELD, ITEM_SPORT_BALL, NATURE_IMPISH, 0, 0, 76, 0, 244, 188, 0, 0, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_WIDE_GUARD, MOVE_HEAVY_SLAM, MOVE_BODY_PRESS, FALSE, FALSE, TYPE_DRAGON
# 387 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Zamazenta_Page1_3:
# 389 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Zamazenta_Page1
	return

Auto_EventScript_Sample_Sets_Zamazenta_Page1_4:
# 391 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Zamazenta_Page1
	return


Auto_EventScript_Sample_Sets_Torkoal_Page1::
# 399 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Torkoal_Page1
# 400 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 402 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Torkoal_Page1_2
# 405 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Torkoal_Page1_3
# 408 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Torkoal_Page1_4
# 410 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Torkoal_Page1_5
# 413 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page11
	return

Auto_EventScript_Sample_Sets_Torkoal_Page1_2:
# 403 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TORKOAL, 65, ITEM_CHARCOAL, ITEM_SPORT_BALL, NATURE_QUIET, 1, 1, 204, 0, 0, 0, 196, 108, 31, 0, 31, 0, 31, 31, MOVE_PROTECT, MOVE_ERUPTION, MOVE_HEAT_WAVE, MOVE_EARTH_POWER, FALSE, FALSE, TYPE_FIRE
# 404 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Torkoal_Page1_3:
# 406 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TORKOAL, 65, ITEM_CHOICE_SPECS, ITEM_SPORT_BALL, NATURE_QUIET, 1, 0, 204, 0, 0, 0, 196, 108, 31, 0, 31, 0, 31, 31, MOVE_ERUPTION, MOVE_HEAT_WAVE, MOVE_WEATHER_BALL, MOVE_EARTH_POWER, FALSE, FALSE, TYPE_FIRE
# 407 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Torkoal_Page1_4:
# 409 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Torkoal_Page1
	return

Auto_EventScript_Sample_Sets_Torkoal_Page1_5:
# 411 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Torkoal_Page1
	return


Auto_EventScript_Sample_Sets_Tornadus_Page1::
# 419 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Tornadus_Page1
# 420 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 422 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Tornadus_Page1_2
# 425 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Tornadus_Page1_3
# 428 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Tornadus_Page1_4
# 431 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Tornadus_Page1_5
# 433 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Tornadus_Page1_6
# 436 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page11
	return

Auto_EventScript_Sample_Sets_Tornadus_Page1_2:
# 423 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TORNADUS, 65, ITEM_COVERT_CLOAK, ITEM_SPORT_BALL, NATURE_BOLD, 0, 0, 196, 0, 228, 4, 4, 76, 31, 0, 31, 31, 31, 31, MOVE_TAUNT, MOVE_TAILWIND, MOVE_RAIN_DANCE, MOVE_BLEAKWIND_STORM, FALSE, FALSE, TYPE_DARK
# 424 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Tornadus_Page1_3:
# 426 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TORNADUS, 65, ITEM_ROCKY_HELMET, ITEM_SPORT_BALL, NATURE_BOLD, 0, 0, 196, 0, 228, 4, 4, 76, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_TAILWIND, MOVE_RAIN_DANCE, MOVE_BLEAKWIND_STORM, FALSE, FALSE, TYPE_DARK
# 427 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Tornadus_Page1_4:
# 429 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TORNADUS, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 4, 0, 0, 252, 252, 0, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_TAILWIND, MOVE_RAIN_DANCE, MOVE_BLEAKWIND_STORM, FALSE, FALSE, TYPE_DARK
# 430 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Tornadus_Page1_5:
# 432 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Tornadus_Page1
	return

Auto_EventScript_Sample_Sets_Tornadus_Page1_6:
# 434 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Tornadus_Page1
	return


Auto_EventScript_Sample_Sets_Tyranitar_Page1::
# 442 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Tyranitar_Page1
# 443 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 445 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Tyranitar_Page1_2
# 448 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Tyranitar_Page1_3
# 450 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Tyranitar_Page1_4
# 453 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page11
	return

Auto_EventScript_Sample_Sets_Tyranitar_Page1_2:
# 446 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TYRANITAR, 65, ITEM_TYRANITARITE, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 1, 44, 164, 20, 252, 0, 28, 31, 31, 31, 31, 31, 31, MOVE_ROCK_SLIDE, MOVE_CRUNCH, MOVE_DRAGON_DANCE, MOVE_PROTECT, FALSE, FALSE, FALSE
# 447 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Tyranitar_Page1_3:
# 449 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Tyranitar_Page1
	return

Auto_EventScript_Sample_Sets_Tyranitar_Page1_4:
# 451 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Tyranitar_Page1
	return


Auto_EventScript_Sample_Sets_Ursaluna_Page1::
# 459 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Ursaluna_Page1
# 460 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 462 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Ursaluna_Page1_2
# 465 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Ursaluna_Page1_3
# 468 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Ursaluna_Page1_4
# 470 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Ursaluna_Page1_5
# 473 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page11
	return

Auto_EventScript_Sample_Sets_Ursaluna_Page1_2:
# 463 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSALUNA, 65, ITEM_FLAME_ORB, ITEM_SPORT_BALL, NATURE_BRAVE, 0, 0, 140, 236, 0, 0, 0, 132, 31, 31, 31, 0, 31, 31, MOVE_PROTECT, MOVE_FACADE, MOVE_EARTHQUAKE, MOVE_HEADLONG_RUSH, FALSE, FALSE, TYPE_GHOST
# 464 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ursaluna_Page1_3:
# 466 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSALUNA, 65, ITEM_FLAME_ORB, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 140, 236, 4, 12, 0, 116, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_FACADE, MOVE_EARTHQUAKE, MOVE_HEADLONG_RUSH, FALSE, FALSE, TYPE_GHOST
# 467 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ursaluna_Page1_4:
# 469 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ursaluna_Page1
	return

Auto_EventScript_Sample_Sets_Ursaluna_Page1_5:
# 471 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ursaluna_Page1
	return


Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1::
# 479 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Ursaluna_Bloodmoon_Page1
# 480 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 482 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_2
# 485 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_3
# 488 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_4
# 491 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_5
# 493 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_6
# 496 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page11
	return

Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_2:
# 483 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSALUNA_BLOODMOON, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 244, 0, 4, 12, 196, 52, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_EARTH_POWER, MOVE_HYPER_VOICE, MOVE_BLOOD_MOON, FALSE, FALSE, TYPE_NORMAL
# 484 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_3:
# 486 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSALUNA_BLOODMOON, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_QUIET, 0, 0, 244, 0, 0, 0, 196, 68, 31, 0, 31, 0, 31, 31, MOVE_PROTECT, MOVE_EARTH_POWER, MOVE_HYPER_VOICE, MOVE_BLOOD_MOON, FALSE, FALSE, TYPE_NORMAL
# 487 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_4:
# 489 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_URSALUNA_BLOODMOON, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 4, 0, 4, 252, 196, 52, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_EARTH_POWER, MOVE_HYPER_VOICE, MOVE_BLOOD_MOON, FALSE, FALSE, TYPE_NORMAL
# 490 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_5:
# 492 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1
	return

Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1_6:
# 494 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ursaluna_Bloodmoon_Page1
	return


Auto_EventScript_Sample_Sets_Roaring_Moon_Page1::
# 502 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Roaring_Moon_Page1
# 503 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 505 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Roaring_Moon_Page1_2
# 508 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Roaring_Moon_Page1_3
# 510 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Roaring_Moon_Page1_4
# 513 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page10
	return

Auto_EventScript_Sample_Sets_Roaring_Moon_Page1_2:
# 506 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_ROARING_MOON, 65, ITEM_BOOSTER_ENERGY, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 0, 4, 220, 28, 252, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_TAILWIND, MOVE_ACROBATICS, MOVE_KNOCK_OFF, FALSE, FALSE, TYPE_FLYING
# 507 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Roaring_Moon_Page1_3:
# 509 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Roaring_Moon_Page1
	return

Auto_EventScript_Sample_Sets_Roaring_Moon_Page1_4:
# 511 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Roaring_Moon_Page1
	return


Auto_EventScript_Sample_Sets_Salamence_Page1::
# 519 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Salamence_Page1
# 520 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 522 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Salamence_Page1_2
# 525 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Salamence_Page1_3
# 528 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Salamence_Page1_4
# 531 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Salamence_Page1_5
# 533 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Salamence_Page1_6
# 536 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page10
	return

Auto_EventScript_Sample_Sets_Salamence_Page1_2:
# 523 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_SALAMENCE, 65, ITEM_SALAMENCITE, ITEM_SPORT_BALL, NATURE_NAIVE, 0, 0, 0, 44, 0, 212, 252, 0, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_TAILWIND, MOVE_HYPER_VOICE, MOVE_DOUBLE_EDGE, FALSE, FALSE, TYPE_WATER
# 524 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Salamence_Page1_3:
# 526 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_SALAMENCE, 65, ITEM_SALAMENCITE, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 252, 36, 4, 92, 0, 124, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_ROOST, MOVE_DOUBLE_EDGE, MOVE_DRAGON_DANCE, FALSE, FALSE, TYPE_WATER
# 527 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Salamence_Page1_4:
# 529 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_SALAMENCE, 65, ITEM_SALAMENCITE, ITEM_SPORT_BALL, NATURE_MODEST, 0, 1, 4, 0, 4, 252, 244, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_TAILWIND, MOVE_HYPER_VOICE, MOVE_DRACO_METEOR, FALSE, FALSE, TYPE_WATER
# 530 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Salamence_Page1_5:
# 532 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Salamence_Page1
	return

Auto_EventScript_Sample_Sets_Salamence_Page1_6:
# 534 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Salamence_Page1
	return


Auto_EventScript_Sample_Sets_Talonflame_Page1::
# 542 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Talonflame_Page1
# 543 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 545 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Talonflame_Page1_2
# 548 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Talonflame_Page1_3
# 551 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Talonflame_Page1_4
# 553 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Talonflame_Page1_5
# 556 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page10
	return

Auto_EventScript_Sample_Sets_Talonflame_Page1_2:
# 546 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TALONFLAME, 65, ITEM_CHOICE_BAND, ITEM_SPORT_BALL, NATURE_ADAMANT, 1, 1, 4, 252, 0, 252, 0, 0, 31, 31, 31, 31, 31, 31, MOVE_BRAVE_BIRD, MOVE_FLARE_BLITZ, MOVE_SLEEP_TALK, MOVE_U_TURN, FALSE, FALSE, TYPE_FLYING
# 547 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Talonflame_Page1_3:
# 549 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TALONFLAME, 65, ITEM_CHOICE_BAND, ITEM_SPORT_BALL, NATURE_JOLLY, 1, 0, 4, 252, 0, 252, 0, 0, 31, 31, 31, 31, 31, 31, MOVE_BRAVE_BIRD, MOVE_FLARE_BLITZ, MOVE_U_TURN, MOVE_TAUNT, FALSE, FALSE, TYPE_FLYING
# 550 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Talonflame_Page1_4:
# 552 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Talonflame_Page1
	return

Auto_EventScript_Sample_Sets_Talonflame_Page1_5:
# 554 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Talonflame_Page1
	return


Auto_EventScript_Sample_Sets_Ting_Lu_Page1::
# 562 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Ting_Lu_Page1
# 563 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 565 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Ting_Lu_Page1_2
# 568 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Ting_Lu_Page1_3
# 570 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Ting_Lu_Page1_4
# 573 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page10
	return

Auto_EventScript_Sample_Sets_Ting_Lu_Page1_2:
# 566 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TING_LU, 65, ITEM_ROCKY_HELMET, ITEM_SPORT_BALL, NATURE_IMPISH, 0, 0, 52, 4, 196, 4, 0, 252, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_SAND_TOMB, MOVE_RUINATION, MOVE_BODY_PRESS, FALSE, FALSE, TYPE_POISON
# 567 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ting_Lu_Page1_3:
# 569 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ting_Lu_Page1
	return

Auto_EventScript_Sample_Sets_Ting_Lu_Page1_4:
# 571 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ting_Lu_Page1
	return


Auto_EventScript_Sample_Sets_Tinkaton_Page1::
# 579 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Tinkaton_Page1
# 580 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 582 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Tinkaton_Page1_2
# 585 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Tinkaton_Page1_3
# 587 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Tinkaton_Page1_4
# 590 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page10
	return

Auto_EventScript_Sample_Sets_Tinkaton_Page1_2:
# 583 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_TINKATON, 65, ITEM_ASSAULT_VEST, ITEM_SPORT_BALL, NATURE_CAREFUL, 0, 1, 180, 172, 100, 12, 0, 44, 31, 31, 31, 31, 31, 31, MOVE_GIGATON_HAMMER, MOVE_PLAY_ROUGH, MOVE_FEINT, MOVE_FAKE_OUT, FALSE, FALSE, TYPE_WATER
# 584 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Tinkaton_Page1_3:
# 586 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Tinkaton_Page1
	return

Auto_EventScript_Sample_Sets_Tinkaton_Page1_4:
# 588 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Tinkaton_Page1
	return


Auto_EventScript_Sample_Sets_Politoed_Page1::
# 596 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Politoed_Page1
# 597 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 599 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Politoed_Page1_2
# 602 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Politoed_Page1_3
# 604 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Politoed_Page1_4
# 607 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page9
	return

Auto_EventScript_Sample_Sets_Politoed_Page1_2:
# 600 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_POLITOED, 65, ITEM_LEFTOVERS, ITEM_SPORT_BALL, NATURE_CALM, 2, 1, 220, 0, 196, 12, 4, 76, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_ENCORE, MOVE_PERISH_SONG, MOVE_SCALD, FALSE, FALSE, TYPE_GRASS
# 601 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Politoed_Page1_3:
# 603 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Politoed_Page1
	return

Auto_EventScript_Sample_Sets_Politoed_Page1_4:
# 605 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Politoed_Page1
	return


Auto_EventScript_Sample_Sets_Porygon2_Page1::
# 613 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Porygon2_Page1
# 614 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 616 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Porygon2_Page1_2
# 619 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Porygon2_Page1_3
# 622 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Porygon2_Page1_4
# 624 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Porygon2_Page1_5
# 627 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page9
	return

Auto_EventScript_Sample_Sets_Porygon2_Page1_2:
# 617 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_PORYGON2, 65, ITEM_EVIOLITE, ITEM_SPORT_BALL, NATURE_MODEST, 1, 0, 244, 0, 92, 4, 116, 52, 31, 0, 31, 31, 31, 31, MOVE_TERA_BLAST, MOVE_ICE_BEAM, MOVE_TRICK_ROOM, MOVE_RECOVER, FALSE, FALSE, TYPE_FLYING
# 618 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Porygon2_Page1_3:
# 620 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_PORYGON2, 65, ITEM_EVIOLITE, ITEM_SPORT_BALL, NATURE_QUIET, 1, 0, 244, 0, 92, 0, 116, 52, 31, 0, 31, 0, 31, 31, MOVE_TERA_BLAST, MOVE_ICE_BEAM, MOVE_TRICK_ROOM, MOVE_RECOVER, FALSE, FALSE, TYPE_FLYING
# 621 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Porygon2_Page1_4:
# 623 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Porygon2_Page1
	return

Auto_EventScript_Sample_Sets_Porygon2_Page1_5:
# 625 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Porygon2_Page1
	return


Auto_EventScript_Sample_Sets_Raging_Bolt_Page1::
# 633 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Raging_Bolt_Page1
# 634 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 636 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Raging_Bolt_Page1_2
# 639 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Raging_Bolt_Page1_3
# 642 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Raging_Bolt_Page1_4
# 644 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Raging_Bolt_Page1_5
# 647 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page9
	return

Auto_EventScript_Sample_Sets_Raging_Bolt_Page1_2:
# 637 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_RAGING_BOLT, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 148, 0, 36, 180, 100, 44, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_THUNDERBOLT, MOVE_DRACO_METEOR, MOVE_THUNDERCLAP, FALSE, FALSE, TYPE_ELECTRIC
# 638 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Raging_Bolt_Page1_3:
# 640 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_RAGING_BOLT, 65, ITEM_ASSAULT_VEST, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 244, 0, 124, 4, 100, 36, 31, 0, 31, 31, 31, 31, MOVE_SNARL, MOVE_THUNDERBOLT, MOVE_DRACO_METEOR, MOVE_THUNDERCLAP, FALSE, FALSE, TYPE_ELECTRIC
# 641 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Raging_Bolt_Page1_4:
# 643 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Raging_Bolt_Page1
	return

Auto_EventScript_Sample_Sets_Raging_Bolt_Page1_5:
# 645 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Raging_Bolt_Page1
	return


Auto_EventScript_Sample_Sets_Regidrago_Page1::
# 653 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Regidrago_Page1
# 654 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 656 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Regidrago_Page1_2
# 659 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Regidrago_Page1_3
# 661 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Regidrago_Page1_4
# 664 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page9
	return

Auto_EventScript_Sample_Sets_Regidrago_Page1_2:
# 657 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_REGIDRAGO, 65, ITEM_DRAGON_FANG, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 12, 0, 4, 252, 236, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_DRAGON_ENERGY, MOVE_DRACO_METEOR, MOVE_EARTH_POWER, FALSE, FALSE, TYPE_STEEL
# 658 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Regidrago_Page1_3:
# 660 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Regidrago_Page1
	return

Auto_EventScript_Sample_Sets_Regidrago_Page1_4:
# 662 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Regidrago_Page1
	return


Auto_EventScript_Sample_Sets_Rillaboom_Page1::
# 670 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Rillaboom_Page1
# 671 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 673 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Rillaboom_Page1_2
# 676 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Rillaboom_Page1_3
# 679 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Rillaboom_Page1_4
# 681 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Rillaboom_Page1_5
# 684 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page9
	return

Auto_EventScript_Sample_Sets_Rillaboom_Page1_2:
# 674 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_RILLABOOM, 65, ITEM_ASSAULT_VEST, ITEM_SPORT_BALL, NATURE_ADAMANT, 1, 1, 140, 116, 12, 4, 0, 236, 31, 31, 31, 31, 31, 31, MOVE_U_TURN, MOVE_WOOD_HAMMER, MOVE_GRASSY_GLIDE, MOVE_FAKE_OUT, FALSE, FALSE, TYPE_FIRE
# 675 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Rillaboom_Page1_3:
# 677 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_RILLABOOM, 65, ITEM_ASSAULT_VEST, ITEM_SPORT_BALL, NATURE_ADAMANT, 1, 1, 140, 196, 12, 4, 0, 156, 31, 31, 31, 31, 31, 31, MOVE_U_TURN, MOVE_WOOD_HAMMER, MOVE_GRASSY_GLIDE, MOVE_FAKE_OUT, FALSE, FALSE, TYPE_FIRE
# 678 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Rillaboom_Page1_4:
# 680 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Rillaboom_Page1
	return

Auto_EventScript_Sample_Sets_Rillaboom_Page1_5:
# 682 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Rillaboom_Page1
	return


Auto_EventScript_Sample_Sets_Miraidon_Page1::
# 690 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Miraidon_Page1
# 691 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 693 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Miraidon_Page1_2
# 696 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Miraidon_Page1_3
# 698 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Miraidon_Page1_4
# 701 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page8
	return

Auto_EventScript_Sample_Sets_Miraidon_Page1_2:
# 694 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_MIRAIDON, 65, ITEM_CHOICE_SPECS, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 92, 0, 4, 212, 196, 4, 31, 31, 31, 31, 31, 31, MOVE_VOLT_SWITCH, MOVE_ELECTRO_DRIFT, MOVE_DRACO_METEOR, MOVE_DAZZLING_GLEAM, FALSE, FALSE, TYPE_FAIRY
# 695 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Miraidon_Page1_3:
# 697 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Miraidon_Page1
	return

Auto_EventScript_Sample_Sets_Miraidon_Page1_4:
# 699 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Miraidon_Page1
	return


Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1::
# 707 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Ogerpon_Cs_Page1
# 708 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 710 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1_2
# 713 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1_3
# 715 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1_4
# 718 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page8
	return

Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1_2:
# 711 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_OGERPON_CORNERSTONE, 65, ITEM_CORNERSTONE_MASK, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 1, 0, 252, 4, 252, 0, 0, 31, 31, 31, 31, 31, 31, MOVE_SPIKY_SHIELD, MOVE_FOLLOW_ME, MOVE_POWER_WHIP, MOVE_IVY_CUDGEL, FALSE, FALSE, TYPE_ROCK
# 712 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1_3:
# 714 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1
	return

Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1_4:
# 716 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ogerpon_Cs_Page1
	return


Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1::
# 724 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Ogerpon_Hf_Page1
# 725 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 727 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1_2
# 730 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1_3
# 733 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1_4
# 735 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1_5
# 738 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page8
	return

Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1_2:
# 728 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_OGERPON_HEARTHFLAME, 65, ITEM_HEARTHFLAME_MASK, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 1, 188, 76, 52, 188, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_SPIKY_SHIELD, MOVE_FOLLOW_ME, MOVE_WOOD_HAMMER, MOVE_IVY_CUDGEL, FALSE, FALSE, TYPE_FIRE
# 729 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1_3:
# 731 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_OGERPON_HEARTHFLAME, 65, ITEM_HEARTHFLAME_MASK, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 1, 28, 220, 4, 252, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_SPIKY_SHIELD, MOVE_FOLLOW_ME, MOVE_WOOD_HAMMER, MOVE_IVY_CUDGEL, FALSE, FALSE, TYPE_FIRE
# 732 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1_4:
# 734 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1
	return

Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1_5:
# 736 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ogerpon_Hf_Page1
	return


Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1::
# 744 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Ogerpon_Ws_Page1
# 745 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 747 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1_2
# 750 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1_3
# 752 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1_4
# 755 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page8
	return

Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1_2:
# 748 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_OGERPON_WELLSPRING, 65, ITEM_WELLSPRING_MASK, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 1, 220, 60, 44, 180, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_SPIKY_SHIELD, MOVE_FOLLOW_ME, MOVE_IVY_CUDGEL, MOVE_HORN_LEECH, FALSE, FALSE, TYPE_WATER
# 749 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1_3:
# 751 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1
	return

Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1_4:
# 753 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Ogerpon_Ws_Page1
	return


Auto_EventScript_Sample_Sets_Pelipper_Page1::
# 761 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Pelipper_Page1
# 762 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 764 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Pelipper_Page1_2
# 767 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Pelipper_Page1_3
# 769 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Pelipper_Page1_4
# 772 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page8
	return

Auto_EventScript_Sample_Sets_Pelipper_Page1_2:
# 765 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_PELIPPER, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_MODEST, 1, 0, 0, 0, 4, 252, 252, 0, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_WIDE_GUARD, MOVE_WEATHER_BALL, MOVE_HURRICANE, FALSE, FALSE, TYPE_GHOST
# 766 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Pelipper_Page1_3:
# 768 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Pelipper_Page1
	return

Auto_EventScript_Sample_Sets_Pelipper_Page1_4:
# 770 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Pelipper_Page1
	return


Auto_EventScript_Sample_Sets_Latias_Page1::
# 778 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Latias_Page1
# 779 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 781 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Latias_Page1_2
# 784 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Latias_Page1_3
# 786 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Latias_Page1_4
# 789 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page7
	return

Auto_EventScript_Sample_Sets_Latias_Page1_2:
# 782 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_LATIAS, 65, ITEM_LATIASITE, ITEM_SPORT_BALL, NATURE_MODEST, 0, 1, 252, 0, 60, 108, 76, 12, 31, 0, 31, 31, 31, 31, MOVE_PSYSHOCK, MOVE_ICE_BEAM, MOVE_CALM_MIND, MOVE_RECOVER, FALSE, FALSE, FALSE
# 783 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Latias_Page1_3:
# 785 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Latias_Page1
	return

Auto_EventScript_Sample_Sets_Latias_Page1_4:
# 787 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Latias_Page1
	return


Auto_EventScript_Sample_Sets_Lunala_Page1::
# 795 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Lunala_Page1
# 796 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 798 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Lunala_Page1_2
# 801 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Lunala_Page1_3
# 803 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Lunala_Page1_4
# 806 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page7
	return

Auto_EventScript_Sample_Sets_Lunala_Page1_2:
# 799 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_LUNALA, 65, ITEM_POWER_HERB, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 140, 0, 132, 52, 180, 4, 31, 0, 31, 31, 31, 31, MOVE_WIDE_GUARD, MOVE_MOONGEIST_BEAM, MOVE_METEOR_BEAM, MOVE_TRICK_ROOM, FALSE, FALSE, TYPE_DARK
# 800 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Lunala_Page1_3:
# 802 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Lunala_Page1
	return

Auto_EventScript_Sample_Sets_Lunala_Page1_4:
# 804 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Lunala_Page1
	return


Auto_EventScript_Sample_Sets_Manectric_Page1::
# 812 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Manectric_Page1
# 813 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 815 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Manectric_Page1_2
# 818 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Manectric_Page1_3
# 820 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Manectric_Page1_4
# 823 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page7
	return

Auto_EventScript_Sample_Sets_Manectric_Page1_2:
# 816 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_MANECTRIC, 65, ITEM_MANECTITE, ITEM_SPORT_BALL, NATURE_TIMID, 1, 1, 244, 0, 4, 220, 36, 4, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_VOLT_SWITCH, MOVE_OVERHEAT, MOVE_SNARL, FALSE, FALSE, TYPE_GRASS
# 817 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Manectric_Page1_3:
# 819 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Manectric_Page1
	return

Auto_EventScript_Sample_Sets_Manectric_Page1_4:
# 821 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Manectric_Page1
	return


Auto_EventScript_Sample_Sets_Mawile_Page1::
# 829 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Mawile_Page1
# 830 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 832 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Mawile_Page1_2
# 835 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Mawile_Page1_3
# 838 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Mawile_Page1_4
# 840 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Mawile_Page1_5
# 843 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page7
	return

Auto_EventScript_Sample_Sets_Mawile_Page1_2:
# 833 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_MAWILE, 65, ITEM_MAWILITE, ITEM_SPORT_BALL, NATURE_BRAVE, 1, 1, 156, 196, 0, 0, 0, 156, 31, 31, 31, 0, 31, 31, MOVE_PROTECT, MOVE_IRON_HEAD, MOVE_PLAY_ROUGH, MOVE_SUCKER_PUNCH, FALSE, FALSE, TYPE_FIRE
# 834 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Mawile_Page1_3:
# 836 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_MAWILE, 65, ITEM_MAWILITE, ITEM_SPORT_BALL, NATURE_ADAMANT, 1, 0, 156, 196, 4, 4, 0, 148, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_IRON_HEAD, MOVE_PLAY_ROUGH, MOVE_SUCKER_PUNCH, FALSE, FALSE, TYPE_FIRE
# 837 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Mawile_Page1_4:
# 839 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Mawile_Page1
	return

Auto_EventScript_Sample_Sets_Mawile_Page1_5:
# 841 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Mawile_Page1
	return


Auto_EventScript_Sample_Sets_Metagross_Page1::
# 849 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Metagross_Page1
# 850 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 852 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Metagross_Page1_2
# 855 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Metagross_Page1_3
# 857 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Metagross_Page1_4
# 860 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page7
	return

Auto_EventScript_Sample_Sets_Metagross_Page1_2:
# 853 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_METAGROSS, 65, ITEM_METAGROSSITE, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 124, 196, 12, 140, 0, 36, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_IRON_HEAD, MOVE_ICE_PUNCH, MOVE_STOMPING_TANTRUM, FALSE, FALSE, TYPE_FIRE
# 854 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Metagross_Page1_3:
# 856 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Metagross_Page1
	return

Auto_EventScript_Sample_Sets_Metagross_Page1_4:
# 858 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Metagross_Page1
	return


Auto_EventScript_Sample_Sets_Kingambit_Page1::
# 866 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Kingambit_Page1
# 867 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 869 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Kingambit_Page1_2
# 872 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Kingambit_Page1_3
# 875 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Kingambit_Page1_4
# 877 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Kingambit_Page1_5
# 880 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page6
	return

Auto_EventScript_Sample_Sets_Kingambit_Page1_2:
# 870 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_KINGAMBIT, 65, ITEM_BLACK_GLASSES, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 1, 204, 196, 4, 12, 0, 92, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_SWORDS_DANCE, MOVE_KOWTOW_CLEAVE, MOVE_SUCKER_PUNCH, FALSE, FALSE, TYPE_DARK
# 871 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Kingambit_Page1_3:
# 873 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_KINGAMBIT, 65, ITEM_ASSAULT_VEST, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 204, 196, 4, 12, 0, 92, 31, 31, 31, 31, 31, 31, MOVE_KOWTOW_CLEAVE, MOVE_SUCKER_PUNCH, MOVE_TERA_BLAST, MOVE_IRON_HEAD, FALSE, FALSE, TYPE_FLYING
# 874 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Kingambit_Page1_4:
# 876 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kingambit_Page1
	return

Auto_EventScript_Sample_Sets_Kingambit_Page1_5:
# 878 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kingambit_Page1
	return


Auto_EventScript_Sample_Sets_Koraidon_Page1::
# 886 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Koraidon_Page1
# 887 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 889 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Koraidon_Page1_2
# 892 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Koraidon_Page1_3
# 895 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Koraidon_Page1_4
# 897 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Koraidon_Page1_5
# 900 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page6
	return

Auto_EventScript_Sample_Sets_Koraidon_Page1_2:
# 890 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_KORAIDON, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 108, 116, 4, 212, 0, 68, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_FLAME_CHARGE, MOVE_CLOSE_COMBAT, MOVE_FLARE_BLITZ, FALSE, FALSE, TYPE_FIRE
# 891 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Koraidon_Page1_3:
# 893 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_KORAIDON, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 0, 28, 220, 4, 252, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_FLAME_CHARGE, MOVE_CLOSE_COMBAT, MOVE_FLARE_BLITZ, FALSE, FALSE, TYPE_FIRE
# 894 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Koraidon_Page1_4:
# 896 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Koraidon_Page1
	return

Auto_EventScript_Sample_Sets_Koraidon_Page1_5:
# 898 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Koraidon_Page1
	return


Auto_EventScript_Sample_Sets_Kyogre_Page1::
# 906 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Kyogre_Page1
# 907 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 909 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Kyogre_Page1_2
# 912 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Kyogre_Page1_3
# 915 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Kyogre_Page1_4
# 918 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Kyogre_Page1_5
# 920 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Kyogre_Page1_6
# 923 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page6
	return

Auto_EventScript_Sample_Sets_Kyogre_Page1_2:
# 910 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_KYOGRE, 65, ITEM_MYSTIC_WATER, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 252, 0, 132, 44, 76, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_WATER_SPOUT, MOVE_ORIGIN_PULSE, MOVE_ICE_BEAM, FALSE, FALSE, TYPE_GRASS
# 911 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Kyogre_Page1_3:
# 913 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_KYOGRE, 65, ITEM_BLUE_ORB, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 252, 0, 164, 12, 76, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_WATER_SPOUT, MOVE_ORIGIN_PULSE, MOVE_ICE_BEAM, FALSE, FALSE, TYPE_GRASS
# 914 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Kyogre_Page1_4:
# 916 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_KYOGRE, 65, ITEM_CHOICE_SCARF, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 4, 0, 4, 252, 244, 4, 31, 0, 31, 31, 31, 31, MOVE_WATER_SPOUT, MOVE_ORIGIN_PULSE, MOVE_SCALD, MOVE_THUNDER, FALSE, FALSE, FALSE
# 917 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Kyogre_Page1_5:
# 919 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kyogre_Page1
	return

Auto_EventScript_Sample_Sets_Kyogre_Page1_6:
# 921 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kyogre_Page1
	return


Auto_EventScript_Sample_Sets_Lando_T_Page1::
# 929 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Lando_T_Page1
# 930 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 932 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Lando_T_Page1_2
# 935 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Lando_T_Page1_3
# 938 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Lando_T_Page1_4
# 941 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Lando_T_Page1_5
# 944 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Lando_T_Page1_6
# 946 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Lando_T_Page1_7
# 949 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page6
	return

Auto_EventScript_Sample_Sets_Lando_T_Page1_2:
# 933 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_LANDORUS_THERIAN, 65, ITEM_CHOICE_SCARF, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 12, 196, 4, 252, 0, 44, 31, 31, 31, 31, 31, 31, MOVE_U_TURN, MOVE_STOMPING_TANTRUM, MOVE_ROCK_SLIDE, MOVE_TERA_BLAST, FALSE, FALSE, TYPE_FLYING
# 934 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Lando_T_Page1_3:
# 936 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_LANDORUS_THERIAN, 65, ITEM_ASSAULT_VEST, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 12, 196, 4, 252, 0, 44, 31, 31, 31, 31, 31, 31, MOVE_U_TURN, MOVE_EARTHQUAKE, MOVE_ROCK_SLIDE, MOVE_SUPERPOWER, FALSE, FALSE, TYPE_WATER
# 937 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Lando_T_Page1_4:
# 939 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_LANDORUS_THERIAN, 65, ITEM_GROUNDIUM_Z, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 156, 116, 36, 92, 0, 108, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_SWORDS_DANCE, MOVE_EARTHQUAKE, MOVE_ROCK_SLIDE, FALSE, FALSE, TYPE_WATER
# 940 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Lando_T_Page1_5:
# 942 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_LANDORUS_THERIAN, 65, ITEM_GROUNDIUM_Z, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 20, 164, 4, 252, 0, 68, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_EARTHQUAKE, MOVE_ROCK_SLIDE, MOVE_SUPERPOWER, FALSE, FALSE, TYPE_WATER
# 943 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Lando_T_Page1_6:
# 945 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Lando_T_Page1
	return

Auto_EventScript_Sample_Sets_Lando_T_Page1_7:
# 947 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Lando_T_Page1
	return


Auto_EventScript_Sample_Sets_Landorus_Page1::
# 955 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Landorus_Page1
# 956 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 958 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Landorus_Page1_2
# 961 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Landorus_Page1_3
# 964 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Landorus_Page1_4
# 966 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Landorus_Page1_5
# 969 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page6
	return

Auto_EventScript_Sample_Sets_Landorus_Page1_2:
# 959 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_LANDORUS, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_MODEST, 1, 0, 132, 0, 4, 252, 116, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_SANDSEAR_STORM, MOVE_EARTH_POWER, MOVE_SLUDGE_BOMB, FALSE, FALSE, TYPE_POISON
# 960 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Landorus_Page1_3:
# 962 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_LANDORUS, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_TIMID, 1, 0, 4, 0, 0, 252, 252, 0, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_SANDSEAR_STORM, MOVE_EARTH_POWER, MOVE_SLUDGE_BOMB, FALSE, FALSE, TYPE_POISON
# 963 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Landorus_Page1_4:
# 965 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Landorus_Page1
	return

Auto_EventScript_Sample_Sets_Landorus_Page1_5:
# 967 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Landorus_Page1
	return


Auto_EventScript_Sample_Sets_Indeedee_F_Page1::
# 975 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Indeedee_F_Page1
# 976 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 978 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Indeedee_F_Page1_2
# 981 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Indeedee_F_Page1_3
# 983 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Indeedee_F_Page1_4
# 986 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page5
	return

Auto_EventScript_Sample_Sets_Indeedee_F_Page1_2:
# 979 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_INDEEDEE_F, 65, ITEM_PSYCHIC_SEED, ITEM_SPORT_BALL, NATURE_CALM, 2, 1, 252, 0, 204, 4, 4, 44, 31, 31, 31, 31, 31, 31, MOVE_FOLLOW_ME, MOVE_HELPING_HAND, MOVE_TRICK_ROOM, MOVE_PSYCHIC, FALSE, FALSE, TYPE_WATER
# 980 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Indeedee_F_Page1_3:
# 982 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Indeedee_F_Page1
	return

Auto_EventScript_Sample_Sets_Indeedee_F_Page1_4:
# 984 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Indeedee_F_Page1
	return


Auto_EventScript_Sample_Sets_Iron_Bundle_Page1::
# 992 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Iron_Bundle_Page1
# 993 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 995 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Iron_Bundle_Page1_2
# 998 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Iron_Bundle_Page1_3
# 1000 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Iron_Bundle_Page1_4
# 1003 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page5
	return

Auto_EventScript_Sample_Sets_Iron_Bundle_Page1_2:
# 996 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_IRON_BUNDLE, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 0, 0, 0, 252, 252, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_ICY_WIND, MOVE_FREEZE_DRY, MOVE_HYDRO_PUMP, FALSE, FALSE, TYPE_GRASS
# 997 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Iron_Bundle_Page1_3:
# 999 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Iron_Bundle_Page1
	return

Auto_EventScript_Sample_Sets_Iron_Bundle_Page1_4:
# 1001 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Iron_Bundle_Page1
	return


Auto_EventScript_Sample_Sets_Iron_Hands_Page1::
# 1009 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Iron_Hands_Page1
# 1010 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1012 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Iron_Hands_Page1_2
# 1015 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Iron_Hands_Page1_3
# 1018 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Iron_Hands_Page1_4
# 1020 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Iron_Hands_Page1_5
# 1023 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page5
	return

Auto_EventScript_Sample_Sets_Iron_Hands_Page1_2:
# 1013 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_IRON_HANDS, 65, ITEM_ASSAULT_VEST, ITEM_SPORT_BALL, NATURE_BRAVE, 0, 0, 100, 156, 0, 0, 0, 252, 31, 31, 31, 31, 31, 31, MOVE_DRAIN_PUNCH, MOVE_WILD_CHARGE, MOVE_HEAVY_SLAM, MOVE_FAKE_OUT, FALSE, FALSE, TYPE_GRASS
# 1014 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Iron_Hands_Page1_3:
# 1016 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_IRON_HANDS, 65, ITEM_ASSAULT_VEST, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 60, 156, 36, 4, 0, 252, 31, 31, 31, 31, 31, 31, MOVE_DRAIN_PUNCH, MOVE_WILD_CHARGE, MOVE_HEAVY_SLAM, MOVE_FAKE_OUT, FALSE, FALSE, TYPE_GRASS
# 1017 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Iron_Hands_Page1_4:
# 1019 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Iron_Hands_Page1
	return

Auto_EventScript_Sample_Sets_Iron_Hands_Page1_5:
# 1021 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Iron_Hands_Page1
	return


Auto_EventScript_Sample_Sets_Kangaskhan_Page1::
# 1029 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Kangaskhan_Page1
# 1030 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1032 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Kangaskhan_Page1_2
# 1035 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Kangaskhan_Page1_3
# 1037 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Kangaskhan_Page1_4
# 1040 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page5
	return

Auto_EventScript_Sample_Sets_Kangaskhan_Page1_2:
# 1033 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_KANGASKHAN, 65, ITEM_KANGASKHANITE, ITEM_SPORT_BALL, NATURE_ADAMANT, 1, 1, 36, 196, 20, 20, 0, 236, 31, 31, 31, 31, 31, 31, MOVE_RETURN, MOVE_LOW_KICK, MOVE_SUCKER_PUNCH, MOVE_FAKE_OUT, FALSE, FALSE, TYPE_GHOST
# 1034 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Kangaskhan_Page1_3:
# 1036 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kangaskhan_Page1
	return

Auto_EventScript_Sample_Sets_Kangaskhan_Page1_4:
# 1038 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kangaskhan_Page1
	return


Auto_EventScript_Sample_Sets_Kartana_Page1::
# 1046 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Kartana_Page1
# 1047 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1049 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Kartana_Page1_2
# 1052 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Kartana_Page1_3
# 1054 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Kartana_Page1_4
# 1057 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page5
	return

Auto_EventScript_Sample_Sets_Kartana_Page1_2:
# 1050 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_KARTANA, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 0, 4, 252, 0, 252, 0, 0, 31, 31, 31, 31, 31, 31, MOVE_LEAF_BLADE, MOVE_SACRED_SWORD, MOVE_TAILWIND, MOVE_DETECT, FALSE, FALSE, FALSE
# 1051 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Kartana_Page1_3:
# 1053 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kartana_Page1
	return

Auto_EventScript_Sample_Sets_Kartana_Page1_4:
# 1055 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Kartana_Page1
	return


Auto_EventScript_Sample_Sets_Gholdengo_Page1::
# 1063 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Gholdengo_Page1
# 1064 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1066 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Gholdengo_Page1_2
# 1069 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Gholdengo_Page1_3
# 1072 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Gholdengo_Page1_4
# 1075 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Gholdengo_Page1_5
# 1077 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Gholdengo_Page1_6
# 1080 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page4
	return

Auto_EventScript_Sample_Sets_Gholdengo_Page1_2:
# 1067 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GHOLDENGO, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 212, 0, 4, 60, 212, 20, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_NASTY_PLOT, MOVE_SHADOW_BALL, MOVE_MAKE_IT_RAIN, FALSE, FALSE, TYPE_WATER
# 1068 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Gholdengo_Page1_3:
# 1070 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GHOLDENGO, 65, ITEM_LEFTOVERS, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 244, 0, 4, 36, 212, 12, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_NASTY_PLOT, MOVE_SHADOW_BALL, MOVE_MAKE_IT_RAIN, FALSE, FALSE, TYPE_WATER
# 1071 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Gholdengo_Page1_4:
# 1073 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GHOLDENGO, 65, ITEM_CHOICE_SPECS, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 36, 0, 4, 252, 212, 4, 31, 0, 31, 31, 31, 31, MOVE_STEEL_BEAM, MOVE_SHADOW_BALL, MOVE_MAKE_IT_RAIN, MOVE_DAZZLING_GLEAM, FALSE, FALSE, TYPE_STEEL
# 1074 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Gholdengo_Page1_5:
# 1076 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Gholdengo_Page1
	return

Auto_EventScript_Sample_Sets_Gholdengo_Page1_6:
# 1078 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Gholdengo_Page1
	return


Auto_EventScript_Sample_Sets_Groudon_Page1::
# 1086 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Groudon_Page1
# 1087 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1089 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Groudon_Page1_2
# 1092 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Groudon_Page1_3
# 1095 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Groudon_Page1_4
# 1098 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Groudon_Page1_5
# 1100 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Groudon_Page1_6
# 1103 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page4
	return

Auto_EventScript_Sample_Sets_Groudon_Page1_2:
# 1090 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GROUDON, 65, ITEM_CLEAR_AMULET, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 252, 156, 4, 12, 0, 84, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_BULK_UP, MOVE_PRECIPICE_BLADES, MOVE_HEAT_CRASH, FALSE, FALSE, TYPE_FIRE
# 1091 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Groudon_Page1_3:
# 1093 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GROUDON, 65, ITEM_RED_ORB, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 252, 156, 4, 12, 0, 84, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_SWORDS_DANCE, MOVE_PRECIPICE_BLADES, MOVE_FIRE_PUNCH, FALSE, FALSE, FALSE
# 1094 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Groudon_Page1_4:
# 1096 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GROUDON, 65, ITEM_RED_ORB, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 4, 0, 4, 252, 244, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_EARTH_POWER, MOVE_ERUPTION, MOVE_ROAR, FALSE, FALSE, FALSE
# 1097 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Groudon_Page1_5:
# 1099 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Groudon_Page1
	return

Auto_EventScript_Sample_Sets_Groudon_Page1_6:
# 1101 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Groudon_Page1
	return


Auto_EventScript_Sample_Sets_Hatterene_Page1::
# 1109 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Hatterene_Page1
# 1110 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1112 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Hatterene_Page1_2
# 1115 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Hatterene_Page1_3
# 1117 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Hatterene_Page1_4
# 1120 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page4
	return

Auto_EventScript_Sample_Sets_Hatterene_Page1_2:
# 1113 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_HATTERENE, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_QUIET, 2, 1, 212, 0, 84, 0, 188, 20, 31, 0, 31, 0, 31, 31, MOVE_PROTECT, MOVE_TRICK_ROOM, MOVE_EXPANDING_FORCE, MOVE_DAZZLING_GLEAM, FALSE, FALSE, TYPE_WATER
# 1114 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Hatterene_Page1_3:
# 1116 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Hatterene_Page1
	return

Auto_EventScript_Sample_Sets_Hatterene_Page1_4:
# 1118 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Hatterene_Page1
	return


Auto_EventScript_Sample_Sets_Heatran_Page1::
# 1126 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Heatran_Page1
# 1127 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1129 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Heatran_Page1_2
# 1132 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Heatran_Page1_3
# 1135 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Heatran_Page1_4
# 1137 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Heatran_Page1_5
# 1140 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page4
	return

Auto_EventScript_Sample_Sets_Heatran_Page1_2:
# 1130 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_HEATRAN, 65, ITEM_SHUCA_BERRY, ITEM_SPORT_BALL, NATURE_MODEST, 0, 1, 244, 0, 4, 20, 236, 4, 31, 0, 31, 31, 31, 31, MOVE_HEAT_WAVE, MOVE_EARTH_POWER, MOVE_SUBSTITUTE, MOVE_PROTECT, FALSE, FALSE, TYPE_GRASS
# 1131 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Heatran_Page1_3:
# 1133 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_HEATRAN, 65, ITEM_LEFTOVERS, ITEM_SPORT_BALL, NATURE_MODEST, 0, 1, 252, 0, 36, 36, 180, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_EARTH_POWER, MOVE_TERA_BLAST, MOVE_HEAT_WAVE, FALSE, FALSE, TYPE_GRASS
# 1134 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Heatran_Page1_4:
# 1136 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Heatran_Page1
	return

Auto_EventScript_Sample_Sets_Heatran_Page1_5:
# 1138 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Heatran_Page1
	return


Auto_EventScript_Sample_Sets_Incineroar_Page1::
# 1146 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Incineroar_Page1
# 1147 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1149 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Incineroar_Page1_2
# 1152 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Incineroar_Page1_3
# 1155 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Incineroar_Page1_4
# 1158 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Incineroar_Page1_5
# 1160 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Incineroar_Page1_6
# 1163 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page4
	return

Auto_EventScript_Sample_Sets_Incineroar_Page1_2:
# 1150 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_INCINEROAR, 65, ITEM_SITRUS_BERRY, ITEM_SPORT_BALL, NATURE_ADAMANT, 1, 1, 236, 36, 4, 28, 0, 204, 31, 31, 31, 31, 31, 31, MOVE_PARTING_SHOT, MOVE_FLARE_BLITZ, MOVE_KNOCK_OFF, MOVE_FAKE_OUT, FALSE, FALSE, TYPE_GHOST
# 1151 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Incineroar_Page1_3:
# 1153 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_INCINEROAR, 65, ITEM_ROCKY_HELMET, ITEM_SPORT_BALL, NATURE_ADAMANT, 1, 1, 236, 4, 236, 4, 0, 28, 31, 31, 31, 31, 31, 31, MOVE_PARTING_SHOT, MOVE_WILL_O_WISP, MOVE_KNOCK_OFF, MOVE_FAKE_OUT, FALSE, FALSE, TYPE_GHOST
# 1154 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Incineroar_Page1_4:
# 1156 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_INCINEROAR, 65, ITEM_SAFETY_GOGGLES, ITEM_SPORT_BALL, NATURE_ADAMANT, 1, 0, 244, 36, 4, 4, 0, 220, 31, 31, 31, 31, 31, 31, MOVE_PARTING_SHOT, MOVE_FLARE_BLITZ, MOVE_KNOCK_OFF, MOVE_FAKE_OUT, FALSE, FALSE, TYPE_GHOST
# 1157 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Incineroar_Page1_5:
# 1159 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Incineroar_Page1
	return

Auto_EventScript_Sample_Sets_Incineroar_Page1_6:
# 1161 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Incineroar_Page1
	return


Auto_EventScript_Sample_Sets_Farigiraf_Page1::
# 1169 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Farigiraf_Page1
# 1170 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1172 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Farigiraf_Page1_2
# 1175 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Farigiraf_Page1_3
# 1177 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Farigiraf_Page1_4
# 1180 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page3
	return

Auto_EventScript_Sample_Sets_Farigiraf_Page1_2:
# 1173 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_FARIGIRAF, 65, ITEM_SITRUS_BERRY, ITEM_SPORT_BALL, NATURE_CALM, 1, 1, 228, 0, 116, 4, 4, 156, 31, 0, 31, 31, 31, 31, MOVE_TRICK_ROOM, MOVE_HELPING_HAND, MOVE_HYPER_VOICE, MOVE_PSYCHIC, FALSE, FALSE, TYPE_WATER
# 1174 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Farigiraf_Page1_3:
# 1176 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Farigiraf_Page1
	return

Auto_EventScript_Sample_Sets_Farigiraf_Page1_4:
# 1178 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Farigiraf_Page1
	return


Auto_EventScript_Sample_Sets_Flutter_Mane_Page1::
# 1186 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Flutter_Mane_Page1
# 1187 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1189 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_2
# 1192 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_3
# 1195 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_4
# 1198 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_5
# 1200 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_6
# 1203 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page3
	return

Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_2:
# 1190 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_FLUTTER_MANE, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 0, 0, 4, 252, 252, 0, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_ICY_WIND, MOVE_MOONBLAST, MOVE_SHADOW_BALL, FALSE, FALSE, TYPE_FAIRY
# 1191 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_3:
# 1193 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_FLUTTER_MANE, 65, ITEM_CHOICE_SPECS, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 116, 0, 156, 196, 36, 4, 31, 0, 31, 31, 31, 31, MOVE_DAZZLING_GLEAM, MOVE_SHADOW_BALL, MOVE_MOONBLAST, MOVE_ICY_WIND, FALSE, FALSE, TYPE_FAIRY
# 1194 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_4:
# 1196 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_FLUTTER_MANE, 65, ITEM_BOOSTER_ENERGY, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 228, 0, 204, 68, 4, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_ICY_WIND, MOVE_MOONBLAST, MOVE_SHADOW_BALL, FALSE, FALSE, TYPE_FAIRY
# 1197 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_5:
# 1199 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Flutter_Mane_Page1
	return

Auto_EventScript_Sample_Sets_Flutter_Mane_Page1_6:
# 1201 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Flutter_Mane_Page1
	return


Auto_EventScript_Sample_Sets_Gardevoir_Page1::
# 1209 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Gardevoir_Page1
# 1210 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1212 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Gardevoir_Page1_2
# 1215 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Gardevoir_Page1_3
# 1217 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Gardevoir_Page1_4
# 1220 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page3
	return

Auto_EventScript_Sample_Sets_Gardevoir_Page1_2:
# 1213 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GARDEVOIR, 65, ITEM_GARDEVOIRITE, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 244, 0, 196, 28, 36, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_HYPER_VOICE, MOVE_TRICK_ROOM, MOVE_PSYCHIC, FALSE, FALSE, TYPE_WATER
# 1214 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Gardevoir_Page1_3:
# 1216 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Gardevoir_Page1
	return

Auto_EventScript_Sample_Sets_Gardevoir_Page1_4:
# 1218 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Gardevoir_Page1
	return


Auto_EventScript_Sample_Sets_Garganacl_Page1::
# 1226 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Garganacl_Page1
# 1227 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1229 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Garganacl_Page1_2
# 1232 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Garganacl_Page1_3
# 1235 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Garganacl_Page1_4
# 1237 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Garganacl_Page1_5
# 1240 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page3
	return

Auto_EventScript_Sample_Sets_Garganacl_Page1_2:
# 1230 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GARGANACL, 65, ITEM_LEFTOVERS, ITEM_SPORT_BALL, NATURE_SASSY, 0, 0, 252, 0, 20, 0, 0, 236, 31, 31, 31, 0, 31, 31, MOVE_PROTECT, MOVE_WIDE_GUARD, MOVE_SALT_CURE, MOVE_RECOVER, FALSE, FALSE, TYPE_GHOST
# 1231 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Garganacl_Page1_3:
# 1233 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GARGANACL, 65, ITEM_LEFTOVERS, ITEM_SPORT_BALL, NATURE_CAREFUL, 0, 1, 252, 4, 12, 4, 0, 236, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_WIDE_GUARD, MOVE_SALT_CURE, MOVE_RECOVER, FALSE, FALSE, TYPE_GHOST
# 1234 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Garganacl_Page1_4:
# 1236 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Garganacl_Page1
	return

Auto_EventScript_Sample_Sets_Garganacl_Page1_5:
# 1238 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Garganacl_Page1
	return


Auto_EventScript_Sample_Sets_Gengar_Page1::
# 1246 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Gengar_Page1
# 1247 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1249 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Gengar_Page1_2
# 1252 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Gengar_Page1_3
# 1255 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Gengar_Page1_4
# 1257 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Gengar_Page1_5
# 1260 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page3
	return

Auto_EventScript_Sample_Sets_Gengar_Page1_2:
# 1250 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GENGAR, 65, ITEM_GENGARITE, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 252, 0, 68, 180, 4, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_SHADOW_BALL, MOVE_PERISH_SONG, MOVE_DISABLE, FALSE, FALSE, TYPE_WATER
# 1251 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Gengar_Page1_3:
# 1253 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_GENGAR, 65, ITEM_GENGARITE, ITEM_SPORT_BALL, NATURE_TIMID, 0, 1, 76, 0, 28, 180, 220, 4, 31, 0, 31, 31, 31, 31, MOVE_SHADOW_BALL, MOVE_SLUDGE_BOMB, MOVE_DISABLE, MOVE_PROTECT, FALSE, FALSE, TYPE_WATER
# 1254 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Gengar_Page1_4:
# 1256 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Gengar_Page1
	return

Auto_EventScript_Sample_Sets_Gengar_Page1_5:
# 1258 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Gengar_Page1
	return


Auto_EventScript_Sample_Sets_Calyrex_Page1::
# 1266 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Calyrex_Page1
# 1267 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1269 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Calyrex_Page1_2
# 1272 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Calyrex_Page1_3
# 1275 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Calyrex_Page1_4
# 1278 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Calyrex_Page1_5
# 1281 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Calyrex_Page1_6
# 1283 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Calyrex_Page1_7
# 1286 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page2
	return

Auto_EventScript_Sample_Sets_Calyrex_Page1_2:
# 1270 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CALYREX, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 0, 0, 4, 252, 252, 0, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_NASTY_PLOT, MOVE_PSYCHIC, MOVE_NONE, FALSE, FALSE, TYPE_GHOST
# 1271 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Calyrex_Page1_3:
# 1273 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CALYREX, 65, ITEM_LIFE_ORB, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 20, 0, 4, 252, 220, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_NASTY_PLOT, MOVE_PSYCHIC, MOVE_NONE, FALSE, FALSE, TYPE_GHOST
# 1274 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Calyrex_Page1_4:
# 1276 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CALYREX, 65, ITEM_CLEAR_AMULET, ITEM_SPORT_BALL, NATURE_BRAVE, 0, 0, 252, 116, 0, 0, 0, 140, 31, 31, 31, 0, 31, 31, MOVE_PROTECT, MOVE_TRICK_ROOM, MOVE_CLOSE_COMBAT, MOVE_NONE, FALSE, FALSE, TYPE_FIRE
# 1277 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Calyrex_Page1_5:
# 1279 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CALYREX, 65, ITEM_CLEAR_AMULET, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 252, 116, 4, 12, 0, 124, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_TRICK_ROOM, MOVE_CLOSE_COMBAT, MOVE_NONE, FALSE, FALSE, TYPE_FIRE
# 1280 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Calyrex_Page1_6:
# 1282 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Calyrex_Page1
	return

Auto_EventScript_Sample_Sets_Calyrex_Page1_7:
# 1284 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Calyrex_Page1
	return


Auto_EventScript_Sample_Sets_Charizard_Page1::
# 1292 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Charizard_Page1
# 1293 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1295 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Charizard_Page1_2
# 1298 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Charizard_Page1_3
# 1301 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Charizard_Page1_4
# 1303 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Charizard_Page1_5
# 1306 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page2
	return

Auto_EventScript_Sample_Sets_Charizard_Page1_2:
# 1296 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CHARIZARD, 65, ITEM_CHARIZARDITE_Y, ITEM_SPORT_BALL, NATURE_MODEST, 0, 1, 204, 0, 108, 188, 4, 4, 31, 0, 31, 31, 31, 31, MOVE_PROTECT, MOVE_SCORCHING_SANDS, MOVE_FLAMETHROWER, MOVE_SOLAR_BEAM, FALSE, FALSE, TYPE_GRASS
# 1297 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Charizard_Page1_3:
# 1299 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CHARIZARD, 65, ITEM_CHARIZARDITE_X, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 0, 236, 44, 4, 220, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_FLARE_BLITZ, MOVE_WILL_O_WISP, MOVE_ROOST, FALSE, FALSE, TYPE_GRASS
# 1300 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Charizard_Page1_4:
# 1302 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Charizard_Page1
	return

Auto_EventScript_Sample_Sets_Charizard_Page1_5:
# 1304 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Charizard_Page1
	return


Auto_EventScript_Sample_Sets_Chi_Yu_Page1::
# 1312 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Chi_Yu_Page1
# 1313 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1315 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Chi_Yu_Page1_2
# 1318 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Chi_Yu_Page1_3
# 1321 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Chi_Yu_Page1_4
# 1323 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Chi_Yu_Page1_5
# 1326 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page2
	return

Auto_EventScript_Sample_Sets_Chi_Yu_Page1_2:
# 1316 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CHI_YU, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_TIMID, 0, 0, 4, 0, 0, 252, 252, 0, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_HEAT_WAVE, MOVE_DARK_PULSE, MOVE_SNARL, FALSE, FALSE, TYPE_GHOST
# 1317 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Chi_Yu_Page1_3:
# 1319 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CHI_YU, 65, ITEM_CHOICE_SCARF, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 52, 0, 4, 252, 196, 4, 31, 31, 31, 31, 31, 31, MOVE_HEAT_WAVE, MOVE_DARK_PULSE, MOVE_OVERHEAT, MOVE_SNARL, FALSE, FALSE, TYPE_GHOST
# 1320 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Chi_Yu_Page1_4:
# 1322 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Chi_Yu_Page1
	return

Auto_EventScript_Sample_Sets_Chi_Yu_Page1_5:
# 1324 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Chi_Yu_Page1
	return


Auto_EventScript_Sample_Sets_Chien_Pao_Page1::
# 1332 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Chien_Pao_Page1
# 1333 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1335 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Chien_Pao_Page1_2
# 1338 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Chien_Pao_Page1_3
# 1340 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Chien_Pao_Page1_4
# 1343 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page2
	return

Auto_EventScript_Sample_Sets_Chien_Pao_Page1_2:
# 1336 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CHIEN_PAO, 65, ITEM_FOCUS_SASH, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 0, 0, 252, 4, 252, 0, 0, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_ICICLE_CRASH, MOVE_SACRED_SWORD, MOVE_SUCKER_PUNCH, FALSE, FALSE, TYPE_GHOST
# 1337 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Chien_Pao_Page1_3:
# 1339 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Chien_Pao_Page1
	return

Auto_EventScript_Sample_Sets_Chien_Pao_Page1_4:
# 1341 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Chien_Pao_Page1
	return


Auto_EventScript_Sample_Sets_Cresselia_Page1::
# 1349 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Cresselia_Page1
# 1350 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1352 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Cresselia_Page1_2
# 1355 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Cresselia_Page1_3
# 1358 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Cresselia_Page1_4
# 1361 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Cresselia_Page1_5
# 1363 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Cresselia_Page1_6
# 1366 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page2
	return

Auto_EventScript_Sample_Sets_Cresselia_Page1_2:
# 1353 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CRESSELIA, 65, ITEM_ROCKY_HELMET, ITEM_SPORT_BALL, NATURE_BOLD, 0, 1, 252, 0, 156, 4, 4, 76, 31, 0, 31, 31, 31, 31, MOVE_LUNAR_BLESSING, MOVE_TRICK_ROOM, MOVE_HELPING_HAND, MOVE_MOONBLAST, FALSE, FALSE, TYPE_FAIRY
# 1354 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Cresselia_Page1_3:
# 1356 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CRESSELIA, 65, ITEM_SAFETY_GOGGLES, ITEM_SPORT_BALL, NATURE_CALM, 0, 1, 252, 0, 172, 4, 4, 76, 31, 0, 31, 31, 31, 31, MOVE_LUNAR_BLESSING, MOVE_TRICK_ROOM, MOVE_HELPING_HAND, MOVE_MOONBLAST, FALSE, FALSE, TYPE_FAIRY
# 1357 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Cresselia_Page1_4:
# 1359 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_CRESSELIA, 65, ITEM_SAFETY_GOGGLES, ITEM_SPORT_BALL, NATURE_SASSY, 0, 1, 252, 0, 180, 0, 0, 76, 31, 0, 31, 0, 31, 31, MOVE_LUNAR_BLESSING, MOVE_TRICK_ROOM, MOVE_HELPING_HAND, MOVE_MOONBLAST, FALSE, FALSE, TYPE_FAIRY
# 1360 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Cresselia_Page1_5:
# 1362 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Cresselia_Page1
	return

Auto_EventScript_Sample_Sets_Cresselia_Page1_6:
# 1364 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Cresselia_Page1
	return


Auto_EventScript_Sample_Sets_Aegislash_Page1::
# 1372 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Aegislash_Page1
# 1373 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1375 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Aegislash_Page1_2
# 1378 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Aegislash_Page1_3
# 1381 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Aegislash_Page1_4
# 1384 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Aegislash_Page1_5
# 1386 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Aegislash_Page1_6
# 1389 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page1
	return

Auto_EventScript_Sample_Sets_Aegislash_Page1_2:
# 1376 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_AEGISLASH, 65, ITEM_GHOSTIUM_Z, ITEM_SPORT_BALL, NATURE_MODEST, 0, 0, 140, 0, 0, 116, 252, 0, 31, 0, 31, 31, 31, 31, MOVE_KINGS_SHIELD, MOVE_SUBSTITUTE, MOVE_SHADOW_BALL, MOVE_FLASH_CANNON, FALSE, FALSE, FALSE
# 1377 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Aegislash_Page1_3:
# 1379 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_AEGISLASH, 65, ITEM_LEFTOVERS, ITEM_SPORT_BALL, NATURE_MODEST, 0, 1, 236, 0, 0, 20, 252, 0, 31, 0, 31, 31, 31, 31, MOVE_SHADOW_BALL, MOVE_KINGS_SHIELD, MOVE_FLASH_CANNON, MOVE_SUBSTITUTE, FALSE, FALSE, TYPE_WATER
# 1380 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Aegislash_Page1_4:
# 1382 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_AEGISLASH, 65, ITEM_WEAKNESS_POLICY, ITEM_SPORT_BALL, NATURE_QUIET, 0, 0, 252, 0, 4, 0, 180, 68, 31, 0, 31, 0, 31, 31, MOVE_SHADOW_BALL, MOVE_FLASH_CANNON, MOVE_WIDE_GUARD, MOVE_KINGS_SHIELD, FALSE, FALSE, FALSE
# 1383 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Aegislash_Page1_5:
# 1385 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Aegislash_Page1
	return

Auto_EventScript_Sample_Sets_Aegislash_Page1_6:
# 1387 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Aegislash_Page1
	return


Auto_EventScript_Sample_Sets_Amoonguss_Page1::
# 1395 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Amoonguss_Page1
# 1396 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1398 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Amoonguss_Page1_2
# 1401 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Amoonguss_Page1_3
# 1404 "data/scripts/sample_sets_options.pory"
	case 2, Auto_EventScript_Sample_Sets_Amoonguss_Page1_4
# 1407 "data/scripts/sample_sets_options.pory"
	case 3, Auto_EventScript_Sample_Sets_Amoonguss_Page1_5
# 1410 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Amoonguss_Page1_6
# 1412 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Amoonguss_Page1_7
# 1415 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page1
	return

Auto_EventScript_Sample_Sets_Amoonguss_Page1_2:
# 1399 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_AMOONGUSS, 65, ITEM_ROCKY_HELMET, ITEM_SPORT_BALL, NATURE_RELAXED, 1, 1, 236, 0, 236, 0, 0, 36, 31, 0, 31, 0, 31, 31, MOVE_PROTECT, MOVE_POLLEN_PUFF, MOVE_RAGE_POWDER, MOVE_SPORE, FALSE, FALSE, TYPE_WATER
# 1400 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Amoonguss_Page1_3:
# 1402 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_AMOONGUSS, 65, ITEM_SITRUS_BERRY, ITEM_SPORT_BALL, NATURE_SASSY, 1, 1, 244, 0, 108, 0, 0, 156, 31, 0, 31, 0, 31, 31, MOVE_PROTECT, MOVE_POLLEN_PUFF, MOVE_RAGE_POWDER, MOVE_SPORE, FALSE, FALSE, TYPE_WATER
# 1403 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Amoonguss_Page1_4:
# 1405 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_AMOONGUSS, 65, ITEM_EJECT_BUTTON, ITEM_SPORT_BALL, NATURE_SASSY, 1, 1, 252, 0, 180, 0, 0, 76, 31, 0, 31, 0, 31, 31, MOVE_PROTECT, MOVE_POLLEN_PUFF, MOVE_SPORE, MOVE_RAGE_POWDER, FALSE, FALSE, TYPE_WATER
# 1406 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Amoonguss_Page1_5:
# 1408 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_AMOONGUSS, 65, ITEM_SITRUS_BERRY, ITEM_SPORT_BALL, NATURE_SASSY, 1, 1, 252, 0, 20, 0, 0, 236, 31, 0, 31, 0, 31, 31, MOVE_PROTECT, MOVE_POLLEN_PUFF, MOVE_RAGE_POWDER, MOVE_SPORE, FALSE, FALSE, TYPE_WATER
# 1409 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Amoonguss_Page1_6:
# 1411 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Amoonguss_Page1
	return

Auto_EventScript_Sample_Sets_Amoonguss_Page1_7:
# 1413 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Amoonguss_Page1
	return


Auto_EventScript_Sample_Sets_Arcanine_Page1::
# 1421 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Arcanine_Page1
# 1422 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1424 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Arcanine_Page1_2
# 1427 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Arcanine_Page1_3
# 1430 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Arcanine_Page1_4
# 1432 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Arcanine_Page1_5
# 1435 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page1
	return

Auto_EventScript_Sample_Sets_Arcanine_Page1_2:
# 1425 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_ARCANINE, 65, ITEM_SAFETY_GOGGLES, ITEM_SPORT_BALL, NATURE_JOLLY, 0, 1, 236, 68, 4, 196, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_EXTREME_SPEED, MOVE_WILL_O_WISP, MOVE_FLARE_BLITZ, FALSE, FALSE, TYPE_FLYING
# 1426 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Arcanine_Page1_3:
# 1428 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_ARCANINE, 65, ITEM_SAFETY_GOGGLES, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 1, 252, 68, 4, 76, 0, 108, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_WILL_O_WISP, MOVE_FLARE_BLITZ, MOVE_SNARL, FALSE, FALSE, TYPE_WATER
# 1429 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Arcanine_Page1_4:
# 1431 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Arcanine_Page1
	return

Auto_EventScript_Sample_Sets_Arcanine_Page1_5:
# 1433 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Arcanine_Page1
	return


Auto_EventScript_Sample_Sets_Archaludon_Page1::
# 1441 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Archaludon_Page1
# 1442 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1444 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Archaludon_Page1_2
# 1447 "data/scripts/sample_sets_options.pory"
	case 1, Auto_EventScript_Sample_Sets_Archaludon_Page1_3
# 1450 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Archaludon_Page1_4
# 1452 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Archaludon_Page1_5
# 1455 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page1
	return

Auto_EventScript_Sample_Sets_Archaludon_Page1_2:
# 1445 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_ARCHALUDON, 65, ITEM_POWER_HERB, ITEM_SPORT_BALL, NATURE_MODEST, 1, 0, 0, 0, 0, 252, 252, 4, 31, 31, 31, 31, 31, 31, MOVE_PROTECT, MOVE_ELECTRO_SHOT, MOVE_FLASH_CANNON, MOVE_DRACO_METEOR, FALSE, FALSE, TYPE_ELECTRIC
# 1446 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Archaludon_Page1_3:
# 1448 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_ARCHALUDON, 65, ITEM_ASSAULT_VEST, ITEM_SPORT_BALL, NATURE_MODEST, 0, 1, 252, 0, 4, 4, 44, 204, 31, 31, 31, 31, 31, 31, MOVE_ELECTRO_SHOT, MOVE_FLASH_CANNON, MOVE_DRAGON_PULSE, MOVE_BODY_PRESS, FALSE, FALSE, TYPE_GRASS
# 1449 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Archaludon_Page1_4:
# 1451 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Archaludon_Page1
	return

Auto_EventScript_Sample_Sets_Archaludon_Page1_5:
# 1453 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Archaludon_Page1
	return


Auto_EventScript_Sample_Sets_Basculegion_Page1::
# 1461 "data/scripts/sample_sets_options.pory"
	multichoice2 0, 0, Auto_Text_Sample_Sets_Basculegion_Page1
# 1462 "data/scripts/sample_sets_options.pory"
	switch VAR_RESULT
# 1464 "data/scripts/sample_sets_options.pory"
	case 0, Auto_EventScript_Sample_Sets_Basculegion_Page1_2
# 1467 "data/scripts/sample_sets_options.pory"
	case MULTI_L_PRESSED, Auto_EventScript_Sample_Sets_Basculegion_Page1_3
# 1469 "data/scripts/sample_sets_options.pory"
	case MULTI_R_PRESSED, Auto_EventScript_Sample_Sets_Basculegion_Page1_4
# 1472 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Page1
	return

Auto_EventScript_Sample_Sets_Basculegion_Page1_2:
# 1465 "data/scripts/sample_sets_options.pory"
	givemon SPECIES_BASCULEGION, 65, ITEM_CHOICE_BAND, ITEM_SPORT_BALL, NATURE_ADAMANT, 0, 0, 164, 220, 4, 116, 0, 4, 31, 31, 31, 31, 31, 31, MOVE_FLIP_TURN, MOVE_AQUA_JET, MOVE_WAVE_CRASH, MOVE_LAST_RESPECTS, FALSE, FALSE, TYPE_WATER
# 1466 "data/scripts/sample_sets_options.pory"
	goto Common_EventScript_Sample_Sets_CheckPurchase
	return

Auto_EventScript_Sample_Sets_Basculegion_Page1_3:
# 1468 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Basculegion_Page1
	return

Auto_EventScript_Sample_Sets_Basculegion_Page1_4:
# 1470 "data/scripts/sample_sets_options.pory"
	goto Auto_EventScript_Sample_Sets_Basculegion_Page1
	return


Auto_EventScript_Sample_Sets_Controls_Text_0:
# 5 "data/scripts/sample_sets_options.pory"
	.string "L: Previous Page                    R: Next Page\nA: Confirm                    B: Go Back$"

Auto_Text_Sample_Sets_Page1::
# 1476 "data/scripts/sample_sets_options.pory"
	.string "AEGISLASH$"
	.string "AMOONGUSS$"
	.string "ARCANINE$"
	.string "ARCHALUDON$"
	.string "BASCULEGION$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page2::
# 1487 "data/scripts/sample_sets_options.pory"
	.string "CALYREX$"
	.string "CHARIZARD$"
	.string "CHI-YU$"
	.string "CHIEN-PAO$"
	.string "CRESSELIA$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page3::
# 1498 "data/scripts/sample_sets_options.pory"
	.string "FARIGIRAF$"
	.string "FLUTTER MANE$"
	.string "GARDEVOIR$"
	.string "GARGANACL$"
	.string "GENGAR$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page4::
# 1509 "data/scripts/sample_sets_options.pory"
	.string "GHOLDENGO$"
	.string "GROUDON$"
	.string "HATTERENE$"
	.string "HEATRAN$"
	.string "INCINEROAR$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page5::
# 1520 "data/scripts/sample_sets_options.pory"
	.string "INDEEDEE-F$"
	.string "IRON BUNDLE$"
	.string "IRON HANDS$"
	.string "KANGASKHAN$"
	.string "KARTANA$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page6::
# 1531 "data/scripts/sample_sets_options.pory"
	.string "KINGAMBIT$"
	.string "KORAIDON$"
	.string "KYOGRE$"
	.string "LANDO-T$"
	.string "LANDORUS$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page7::
# 1542 "data/scripts/sample_sets_options.pory"
	.string "LATIAS$"
	.string "LUNALA$"
	.string "MANECTRIC$"
	.string "MAWILE$"
	.string "METAGROSS$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page8::
# 1553 "data/scripts/sample_sets_options.pory"
	.string "MIRAIDON$"
	.string "OGERPON-CS$"
	.string "OGERPON-HF$"
	.string "OGERPON-WS$"
	.string "PELIPPER$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page9::
# 1564 "data/scripts/sample_sets_options.pory"
	.string "POLITOED$"
	.string "PORYGON2$"
	.string "RAGING BOLT$"
	.string "REGIDRAGO$"
	.string "RILLABOOM$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page10::
# 1575 "data/scripts/sample_sets_options.pory"
	.string "ROARING MOON$"
	.string "SALAMENCE$"
	.string "TALONFLAME$"
	.string "TING-LU$"
	.string "TINKATON$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page11::
# 1586 "data/scripts/sample_sets_options.pory"
	.string "TORKOAL$"
	.string "TORNADUS$"
	.string "TYRANITAR$"
	.string "URSALUNA$"
	.string "URSALUNA-BLOODMOON$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Page12::
# 1597 "data/scripts/sample_sets_options.pory"
	.string "URSHIFU-RS$"
	.string "URSHIFU-SS$"
	.string "XERNEAS$"
	.string "ZACIAN$"
	.string "ZAMAZENTA$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Urshifu_Rs_Page1::
# 1608 "data/scripts/sample_sets_options.pory"
	.string "0/252+/0/0-/4/252 (SASH)$"
	.string "12/156+/4/0-/84/252 (MYSTIC)$"
	.string "12/156+/4/0-/84/252 (SCARF)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Urshifu_Ss_Page1::
# 1617 "data/scripts/sample_sets_options.pory"
	.string "0/236+/0/0-/20/252 (BAND)$"
	.string "0/252+/0/0-/4/252 (SASH)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Xerneas_Page1::
# 1625 "data/scripts/sample_sets_options.pory"
	.string "4/0-/4/244/4/252+$"
	.string "44/0-/20/188/4/252+$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Zacian_Page1::
# 1633 "data/scripts/sample_sets_options.pory"
	.string "252/76+/4/0-/12/164 (GROUND)$"
	.string "252/76+/4/0-/12/164 (STELLAR)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Zamazenta_Page1::
# 1641 "data/scripts/sample_sets_options.pory"
	.string "76/0/244+/0-/0/188$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Torkoal_Page1::
# 1648 "data/scripts/sample_sets_options.pory"
	.string "204/0/0/196+/108/0-$"
	.string "204/0/0/196+/108/0- (SPECS)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Tornadus_Page1::
# 1656 "data/scripts/sample_sets_options.pory"
	.string "196/0-/228+/4/76/4 (CLOAK)$"
	.string "196/0-/228+/4/76/4 (HELMET)$"
	.string "4/0-/0/252/0/252+ (SASH)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Tyranitar_Page1::
# 1665 "data/scripts/sample_sets_options.pory"
	.string "44/164/20/0-/28/252+$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Ursaluna_Page1::
# 1672 "data/scripts/sample_sets_options.pory"
	.string "140/236+/0/0/132/0-$"
	.string "140/236+/4/0-/116/12$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Ursaluna_Bloodmoon_Page1::
# 1680 "data/scripts/sample_sets_options.pory"
	.string "244/0-/4/196+/52/12 (ORB)$"
	.string "244/0/0/196+/68/0- (ORB)$"
	.string "4/0-/4/196+/52/252 (ORB)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Roaring_Moon_Page1::
# 1689 "data/scripts/sample_sets_options.pory"
	.string "4/220/28/0-/4/252+ (BOOSTER)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Salamence_Page1::
# 1696 "data/scripts/sample_sets_options.pory"
	.string "0/44/0/252/0-/212+ (MEGA)$"
	.string "252/36+/4/0-/124/92 (MEGA)$"
	.string "4/0-/4/244+/4/252$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Talonflame_Page1::
# 1705 "data/scripts/sample_sets_options.pory"
	.string "4/252+/0/0-/0/252 (BANDED)$"
	.string "4/252/0/0-/0/252+ (BANDED)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Ting_Lu_Page1::
# 1713 "data/scripts/sample_sets_options.pory"
	.string "52/4/196+/0-/252/4 (HELMET)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Tinkaton_Page1::
# 1720 "data/scripts/sample_sets_options.pory"
	.string "180/172/100/0-/44+/12$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Politoed_Page1::
# 1727 "data/scripts/sample_sets_options.pory"
	.string "220/0-/196/4/76+/12$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Porygon2_Page1::
# 1734 "data/scripts/sample_sets_options.pory"
	.string "244/0-/92/116+/52/4$"
	.string "244/0/92/116+/52/0-$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Raging_Bolt_Page1::
# 1742 "data/scripts/sample_sets_options.pory"
	.string "148/0-/36/100+/44/180 (ORB)$"
	.string "244/0-/124/100+/36/4 (VEST)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Regidrago_Page1::
# 1750 "data/scripts/sample_sets_options.pory"
	.string "12/0-/4/236+/4/252$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Rillaboom_Page1::
# 1757 "data/scripts/sample_sets_options.pory"
	.string "140/116+/12/0-/236/4 (VEST)$"
	.string "140/196+/12/0-/156/4 (VEST)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Miraidon_Page1::
# 1765 "data/scripts/sample_sets_options.pory"
	.string "92/0-/4/196+/4/212 (SPECS)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Ogerpon_Cs_Page1::
# 1772 "data/scripts/sample_sets_options.pory"
	.string "0/252/4/0-/0/252+$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Ogerpon_Hf_Page1::
# 1779 "data/scripts/sample_sets_options.pory"
	.string "188/76+/52/0-/4/188$"
	.string "28/220/4/0-/4/252+$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Ogerpon_Ws_Page1::
# 1787 "data/scripts/sample_sets_options.pory"
	.string "220/60/44/0-/4/180+$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Pelipper_Page1::
# 1794 "data/scripts/sample_sets_options.pory"
	.string "0/0-/4/252+/0/252 (SASH)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Latias_Page1::
# 1801 "data/scripts/sample_sets_options.pory"
	.string "252/0-/60/76+/12/108$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Lunala_Page1::
# 1808 "data/scripts/sample_sets_options.pory"
	.string "140/0-/132/180+/4/52 (HERB)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Manectric_Page1::
# 1815 "data/scripts/sample_sets_options.pory"
	.string "244/0-/4/36/4/220+ (MEGA)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Mawile_Page1::
# 1822 "data/scripts/sample_sets_options.pory"
	.string "156/196+/0/0/156/0- (MEGA)$"
	.string "156/196+/4/0-/148/4 (MEGA)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Metagross_Page1::
# 1830 "data/scripts/sample_sets_options.pory"
	.string "124/196+/12/0-/36/140 (MEGA)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Kingambit_Page1::
# 1837 "data/scripts/sample_sets_options.pory"
	.string "204/196+/4/0-/92/12$"
	.string "204/196+/4/0-/92/12 (VEST)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Koraidon_Page1::
# 1845 "data/scripts/sample_sets_options.pory"
	.string "108/116+/4/0-/68/212 (ORB)$"
	.string "28/220/4/0-/4/252+ (ORB)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Kyogre_Page1::
# 1853 "data/scripts/sample_sets_options.pory"
	.string "252/0-/132/76+/4/44 (MYSTIC)$"
	.string "252/0-/164/76+/4/12 (PRIMAL)$"
	.string "4/0-/4/244+/4/252 (SCARF)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Lando_T_Page1::
# 1862 "data/scripts/sample_sets_options.pory"
	.string "12/196+/4/0-/44/252 (SCARF)$"
	.string "12/196+/4/0-/44/252 (VEST)$"
	.string "156/116+/36/0-/108/92 (GROUND Z)$"
	.string "20/164+/4/0-/68/252 (GROUND Z)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Landorus_Page1::
# 1872 "data/scripts/sample_sets_options.pory"
	.string "132/0-/4/116+/4/252 (ORB)$"
	.string "4/0-/0/252/0/252+ (SASH)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Indeedee_F_Page1::
# 1880 "data/scripts/sample_sets_options.pory"
	.string "252/0-/204/4/44+/4 (SEED)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Iron_Bundle_Page1::
# 1887 "data/scripts/sample_sets_options.pory"
	.string "0/0-/0/252/4/252+$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Iron_Hands_Page1::
# 1894 "data/scripts/sample_sets_options.pory"
	.string "100/156+/0/0/252/0- (VEST)$"
	.string "60/156+/36/0-/252/4 (VEST)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Kangaskhan_Page1::
# 1902 "data/scripts/sample_sets_options.pory"
	.string "36/196+/20/0-/236/20 (MEGA)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Kartana_Page1::
# 1909 "data/scripts/sample_sets_options.pory"
	.string "4/252/0/0-/0/252+$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Gholdengo_Page1::
# 1916 "data/scripts/sample_sets_options.pory"
	.string "212/0-/4/212+/20/60 (ORB)$"
	.string "244/0-/4/212+/12/36 (LEFTYS)$"
	.string "36/0-/4/212+/4/252 (SPECS)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Groudon_Page1::
# 1925 "data/scripts/sample_sets_options.pory"
	.string "252/156+/4/0-/84/12 (AMULET)$"
	.string "252/156+/4/0-/84/12 (PRIMAL)$"
	.string "4/0-/4/244/4/252+ (PRIMAL)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Hatterene_Page1::
# 1934 "data/scripts/sample_sets_options.pory"
	.string "212/0/84/188+/20/0- (ORB)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Heatran_Page1::
# 1941 "data/scripts/sample_sets_options.pory"
	.string "244/0-/4/236+/4/20 (SHUCA)$"
	.string "252/0-/36/180+/4/36 (LEFTYS)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Incineroar_Page1::
# 1949 "data/scripts/sample_sets_options.pory"
	.string "236/36+/4/0-/204/28 (SITRUS)$"
	.string "236/4+/236/0-/28/4 (HELMET)$"
	.string "244/36+/4/0-/220/4 (GOGGLES)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Farigiraf_Page1::
# 1958 "data/scripts/sample_sets_options.pory"
	.string "228/0-/116/4/156+/4 (SITRUS)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Flutter_Mane_Page1::
# 1965 "data/scripts/sample_sets_options.pory"
	.string "0/0-/4/252/0/252+ (SASH)$"
	.string "116/0-/156/36+/4/196 (SPECS)$"
	.string "228/0-/204/4/4/68+ (BOOSTER)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Gardevoir_Page1::
# 1974 "data/scripts/sample_sets_options.pory"
	.string "244/0-/196/36+/4/28 (MEGA)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Garganacl_Page1::
# 1981 "data/scripts/sample_sets_options.pory"
	.string "252/0/20/0/236+/0-$"
	.string "252/4/12/0-/236+/4$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Gengar_Page1::
# 1989 "data/scripts/sample_sets_options.pory"
	.string "252/0-/68/4/4/180+ (PERISH)$"
	.string "76/0-/28/220/4/180+ (CONTROL)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Calyrex_Page1::
# 1997 "data/scripts/sample_sets_options.pory"
	.string "0/0-/4/252/0/252+ (SHADOW)$"
	.string "20/0-/4/220/4/252+ (SHADOW)$"
	.string "252/116+/0/0/140/0- (ICE)$"
	.string "252/116+/4/0-/124/12 (ICE)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Charizard_Page1::
# 2007 "data/scripts/sample_sets_options.pory"
	.string "204/0-/108/4+/4/188 (MEGA Y)$"
	.string "236/44/4/0-/4/220+ (MEGA X)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Chi_Yu_Page1::
# 2015 "data/scripts/sample_sets_options.pory"
	.string "4/0-/0/252/0/252+ (SASH)$"
	.string "52/0-/4/196+/4/252 (SCARF)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Chien_Pao_Page1::
# 2023 "data/scripts/sample_sets_options.pory"
	.string "0/252/4/0-/0/252+ (SASH)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Cresselia_Page1::
# 2030 "data/scripts/sample_sets_options.pory"
	.string "252/0-/156+/4/76/4 (HELMET)$"
	.string "252/0-/172/4/76+/4 (GOGGLES)$"
	.string "252/0/180/0/76+/0- (GOGGLES)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Aegislash_Page1::
# 2039 "data/scripts/sample_sets_options.pory"
	.string "140/0-/0/252+/0/116 (GHOST Z)$"
	.string "236/0-/0/252+/0/20 (LEFTYS)$"
	.string "252/0/4/180+/68/0- (POLICY)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Amoonguss_Page1::
# 2048 "data/scripts/sample_sets_options.pory"
	.string "236/0/236+/0/36/0- (HELMET)$"
	.string "244/0/108/0/156+/0- (SITRUS)$"
	.string "252/0/180/0/76+/0- (EJECT)$"
	.string "252/0/20/0/236+/0- (SITRUS)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Arcanine_Page1::
# 2058 "data/scripts/sample_sets_options.pory"
	.string "236/68/4/0-/4/196+ (GOGGLES)$"
	.string "252/68+/4/0-/108/76 (GOGGLES)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Archaludon_Page1::
# 2066 "data/scripts/sample_sets_options.pory"
	.string "0/0-/0/252+/4/252 (HERB)$"
	.string "252/0-/4/44+/204/4 (VEST)$"
	.string "Go Back$"
	.string "$"

Auto_Text_Sample_Sets_Basculegion_Page1::
# 2074 "data/scripts/sample_sets_options.pory"
	.string "164/220+/4/0-/4/116$"
	.string "Go Back$"
	.string "$"
