#include "global.h"
#include "money.h"
#include "item.h"
#include "move.h"

#include "event_data.h"
#include "new_game.h"
#include "pokedex.h"

#include "constants/battle_frontier_generator.h"
#include "config/battle_frontier_generator.h"

#include "config/item.h"
#include "config/ebr.h"
#include "ebr_init.h"

#if EBR_QUICK_START_ENABLED == TRUE
static void SetQuickStartFlags(void);
static void SetQuickStartVars(void);
static void GiveQuickStartItems(void);

static void UpdatePokedex(struct Pokemon * mon);
static void GiveVolcarona(void);
static void GiveSmeargle(void);
#endif // EBR_QUICK_START_ENABLED

void EbrQuickStart(void) 
{
    // Quick Start Enabled
    #if EBR_QUICK_START_ENABLED == TRUE

    // Basic Setup
    SetQuickStartFlags();
    SetQuickStartVars();
    GiveQuickStartItems();

	// Battle Lead
	GiveVolcarona();

	// HM Slave
	GiveSmeargle();

    // Give the player's starting funds
    AddMoney(&gSaveBlock1Ptr->money, EBR_QUICK_START_MONEY);
    
    // Enable National Dex
    EnableNationalPokedex();

    #endif
}

#if EBR_QUICK_START_ENABLED == TRUE
static void SetQuickStartFlags(void)
{
    // Running Shoes
    FlagSet(FLAG_SYS_B_DASH);
    FlagSet(FLAG_RECEIVED_RUNNING_SHOES);

    // Male Player
    if (gSaveBlock2Ptr->playerGender == MALE) {
		// Player (Brendan) Flags
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_SIBLING);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_BRENDAN);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_MOM);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_SWABLU_DOLL);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_POKE_BALL);
        
        // Rival Flags
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MOM);
    } 
    else // Female Player
    {
		// Player (May) Flags
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_BEDROOM);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_SIBLING);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MAY);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_MOM);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_POKE_BALL);
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_PICHU_DOLL);

        // Rival Flags
		FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_MOM);
    }

    // General Flags
	FlagSet(FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA_STILL);
	FlagSet(FLAG_SET_WALL_CLOCK);
	FlagSet(FLAG_RESCUED_BIRCH);
	FlagSet(FLAG_HIDE_CONTEST_POKE_BALL);
	FlagSet(FLAG_MET_RIVAL_MOM);
	FlagSet(FLAG_BIRCH_AIDE_MET);
	FlagSet(FLAG_RECEIVED_BIKE);
	FlagSet(FLAG_WATTSON_REMATCH_AVAILABLE);
	FlagSet(FLAG_MET_TEAM_AQUA_HARBOR);
	FlagSet(FLAG_TV_EXPLAINED);
	FlagSet(FLAG_WHITEOUT_TO_LAVARIDGE);
	FlagSet(FLAG_GROUDON_AWAKENED_MAGMA_HIDEOUT);
	FlagSet(FLAG_TEAM_AQUA_ESCAPED_IN_SUBMARINE);
	FlagSet(FLAG_TEAM_AQUA_ESCAPED_IN_SUBMARINE);
	FlagSet(FLAG_RECEIVED_METEORITE);
	FlagSet(FLAG_MET_HIDDEN_POWER_GIVER);
	FlagSet(FLAG_DEFEATED_WALLY_VICTORY_ROAD);
	FlagSet(FLAG_KYOGRE_ESCAPED_SEAFLOOR_CAVERN);
	FlagSet(FLAG_DEFEATED_RIVAL_ROUTE103);
	FlagSet(FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY);
	FlagSet(FLAG_RECOVERED_DEVON_GOODS);
	FlagSet(FLAG_RETURNED_DEVON_GOODS);
	FlagSet(FLAG_MR_BRINEY_SAILING_INTRO);
	FlagSet(FLAG_DOCK_REJECTED_DEVON_GOODS);
	FlagSet(FLAG_DELIVERED_DEVON_GOODS);
	FlagSet(FLAG_SOOTOPOLIS_ARCHIE_MAXIE_LEAVE);
	FlagSet(FLAG_INTERACTED_WITH_DEVON_EMPLOYEE_GOODS_STOLEN);
	FlagSet(FLAG_HIDE_SECRET_BASE_TRAINER);
	FlagSet(FLAG_RECEIVED_POKENAV);
	FlagSet(FLAG_DELIVERED_STEVEN_LETTER);
	FlagSet(FLAG_DEFEATED_WALLY_MAUVILLE);
	FlagSet(FLAG_DEFEATED_GRUNT_SPACE_CENTER_1F);
	FlagSet(FLAG_WALLY_SPEECH);
	FlagSet(FLAG_RUSTURF_TUNNEL_OPENED);
	FlagSet(FLAG_INTERACTED_WITH_STEVEN_SPACE_CENTER);
	FlagSet(FLAG_MET_ARCHIE_METEOR_FALLS);
	FlagSet(FLAG_GOT_BASEMENT_KEY_FROM_WATTSON);
	FlagSet(FLAG_GOT_TM_THUNDERBOLT_FROM_WATTSON);
	FlagSet(FLAG_DEFEATED_RIVAL_RUSTBORO);
	FlagSet(FLAG_RECEIVED_RED_OR_BLUE_ORB);
	FlagSet(FLAG_ENABLE_WALLY_MATCH_CALL);
	FlagSet(FLAG_ENABLE_SCOTT_MATCH_CALL);
	FlagSet(FLAG_ENABLE_MOM_MATCH_CALL);
	FlagSet(FLAG_MET_WAILMER_TRAINER);
	FlagSet(FLAG_EVIL_LEADER_PLEASE_STOP);
	FlagSet(FLAG_RECEIVED_GO_GOGGLES);
	FlagSet(FLAG_MET_PROF_COZMO);
	FlagSet(FLAG_ENABLE_RIVAL_MATCH_CALL);
	FlagSet(FLAG_LATIOS_OR_LATIAS_ROAMING);
	FlagSet(FLAG_ENTERED_ELITE_FOUR);
	FlagSet(FLAG_EVIL_TEAM_ESCAPED_STERN_SPOKE);
	FlagSet(FLAG_RECEIVED_RUNNING_SHOES);
	FlagSet(FLAG_ENABLE_PROF_BIRCH_MATCH_CALL);
	FlagSet(FLAG_RECEIVED_DEVON_SCOPE);
	FlagSet(FLAG_MET_RIVAL_RUSTBORO);
	FlagSet(FLAG_RECEIVED_SS_TICKET);
	FlagSet(FLAG_MET_RIVAL_LILYCOVE);
	FlagSet(FLAG_KECLEON_FLED_FORTREE);
	FlagSet(FLAG_PETALBURG_MART_EXPANDED_ITEMS);
	FlagSet(FLAG_RIVAL_LEFT_FOR_ROUTE103);
	FlagSet(FLAG_OMIT_DIVE_FROM_STEVEN_LETTER);
	FlagSet(FLAG_HAS_MATCH_CALL);
	FlagSet(FLAG_ADDED_MATCH_CALL_TO_POKENAV);
	FlagSet(FLAG_REGISTERED_STEVEN_POKENAV);
	FlagSet(FLAG_ENABLE_NORMAN_MATCH_CALL);
	FlagSet(FLAG_STEVEN_GUIDES_TO_CAVE_OF_ORIGIN);
	FlagSet(FLAG_MET_ARCHIE_SOOTOPOLIS);
	FlagSet(FLAG_MET_MAXIE_SOOTOPOLIS);
	FlagSet(FLAG_WALLACE_GOES_TO_SKY_PILLAR);
	FlagSet(FLAG_BEAT_MAGMA_GRUNT_JAGGED_PASS);
	FlagSet(FLAG_MIRAGE_TOWER_VISIBLE);
	FlagSet(FLAG_ENABLE_MR_STONE_POKENAV);
	FlagSet(FLAG_DEFEATED_ELECTRODE_1_AQUA_HIDEOUT);
	FlagSet(FLAG_DEFEATED_ELECTRODE_2_AQUA_HIDEOUT);
	FlagSet(FLAG_MET_SCOTT_IN_EVERGRANDE);
	FlagSet(FLAG_MET_SCOTT_ON_SS_TIDAL);
	FlagSet(FLAG_MET_SCOTT_ON_SS_TIDAL);

    // Match Call
	FlagSet(FLAG_ENABLE_ROXANNE_MATCH_CALL);
	FlagSet(FLAG_ENABLE_BRAWLY_MATCH_CALL);
	FlagSet(FLAG_ENABLE_WATTSON_MATCH_CALL);
	FlagSet(FLAG_ENABLE_FLANNERY_MATCH_CALL);
	FlagSet(FLAG_ENABLE_WINONA_MATCH_CALL);
	FlagSet(FLAG_ENABLE_TATE_AND_LIZA_MATCH_CALL);
	FlagSet(FLAG_ENABLE_JUAN_MATCH_CALL);

    // Hidden Object Flags
	FlagSet(FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG);
	FlagSet(FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN);
	FlagSet(FLAG_HIDE_SAFARI_ZONE_SOUTH_CONSTRUCTION_WORKERS);
	FlagSet(FLAG_HIDE_ROUTE_104_RIVAL);
	FlagSet(FLAG_HIDE_ROUTE_101_BIRCH_ZIGZAGOON_BATTLE);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_BEDROOM);
	FlagSet(FLAG_HIDE_ROUTE_103_RIVAL);
	FlagSet(FLAG_HIDE_PETALBURG_WOODS_DEVON_EMPLOYEE);
	FlagSet(FLAG_HIDE_PETALBURG_WOODS_AQUA_GRUNT);
	FlagSet(FLAG_HIDE_PETALBURG_CITY_WALLY);
	FlagSet(FLAG_HIDE_PETALBURG_CITY_WALLYS_MOM);
	FlagSet(FLAG_HIDE_RUSTBORO_CITY_AQUA_GRUNT);
	FlagSet(FLAG_HIDE_RUSTBORO_CITY_DEVON_EMPLOYEE_1);
	FlagSet(FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE_ASLEEP);
	FlagSet(FLAG_HIDE_PLAYERS_HOUSE_DAD);
	FlagSet(FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_MAGMA_NOTE);
	FlagSet(FLAG_HIDE_ROUTE_104_MR_BRINEY);
	FlagSet(FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY);
	FlagSet(FLAG_HIDE_MR_BRINEY_DEWFORD_TOWN);
	FlagSet(FLAG_HIDE_ROUTE_109_MR_BRINEY);
	FlagSet(FLAG_HIDE_ROUTE_104_MR_BRINEY_BOAT);
	FlagSet(FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD_TOWN);
	FlagSet(FLAG_HIDE_ROUTE_109_MR_BRINEY_BOAT);
	FlagSet(FLAG_HIDE_LILYCOVE_HARBOR_EVENT_TICKET_TAKER);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_SCOTT);
	FlagSet(FLAG_HIDE_ROUTE_101_ZIGZAGOON);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE);
	FlagSet(FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_STEVEN);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_HOUSE_VIGOROTH_1);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_HOUSE_VIGOROTH_2);
	FlagSet(FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_TEAM_MAGMA);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_BEDROOM_MOM);
	FlagSet(FLAG_HIDE_DEOXYS);
	FlagSet(FLAG_HIDE_BIRTH_ISLAND_DEOXYS_TRIANGLE);
	FlagSet(FLAG_HIDE_MAUVILLE_CITY_SCOTT);
	FlagSet(FLAG_HIDE_VERDANTURF_TOWN_SCOTT);
	FlagSet(FLAG_HIDE_FALLARBOR_TOWN_BATTLE_TENT_SCOTT);
	FlagSet(FLAG_HIDE_ROUTE_111_VICTOR_WINSTRATE);
	FlagSet(FLAG_HIDE_ROUTE_111_VICTORIA_WINSTRATE);
	FlagSet(FLAG_HIDE_ROUTE_111_VIVI_WINSTRATE);
	FlagSet(FLAG_HIDE_ROUTE_111_VICKY_WINSTRATE);
	FlagSet(FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA);
	FlagSet(FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_1);
	FlagSet(FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_1);
	FlagSet(FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_2);
	FlagSet(FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_3);
	FlagSet(FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_4);
	FlagSet(FLAG_HIDE_LILYCOVE_MUSEUM_TOURISTS);
	FlagSet(FLAG_HIDE_PETALBURG_GYM_GREETER);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_MOM);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_MOM);
	FlagSet(FLAG_HIDE_ROUTE_119_SCOTT);
	FlagSet(FLAG_HIDE_LILYCOVE_MOTEL_SCOTT);
	FlagSet(FLAG_HIDE_MOSSDEEP_CITY_SCOTT);
	FlagSet(FLAG_HIDE_EVER_GRANDE_POKEMON_CENTER_1F_SCOTT);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_RIVAL);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BIRCH);
	FlagSet(FLAG_HIDE_ROUTE_111_GABBY_AND_TY_1);
	FlagSet(FLAG_HIDE_ROUTE_118_GABBY_AND_TY_1);
	FlagSet(FLAG_HIDE_ROUTE_120_GABBY_AND_TY_1);
	FlagSet(FLAG_HIDE_ROUTE_111_GABBY_AND_TY_3);
	FlagSet(FLAG_HIDE_LILYCOVE_CONTEST_HALL_REPORTER);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_CONTEST_REPORTER);
	FlagSet(FLAG_HIDE_MAUVILLE_CITY_WALLY);
	FlagSet(FLAG_HIDE_MAUVILLE_CITY_WALLYS_UNCLE);
	FlagSet(FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLY);
	FlagSet(FLAG_HIDE_RUSTURF_TUNNEL_WANDAS_BOYFRIEND);
	FlagSet(FLAG_HIDE_SS_TIDAL_CORRIDOR_SCOTT);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CYNDAQUIL);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_TOTODILE);
	FlagSet(FLAG_HIDE_RUSTBORO_CITY_RIVAL);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_SWABLU_DOLL);
	FlagSet(FLAG_HIDE_SOOTOPOLIS_CITY_WALLACE);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_POKE_BALL);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_POKE_BALL);
	FlagSet(FLAG_HIDE_ROUTE_112_TEAM_MAGMA);
	FlagSet(FLAG_HIDE_CAVE_OF_ORIGIN_B1F_WALLACE);
	FlagSet(FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_1_BLOCKING_ENTRANCE);
	FlagSet(FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_2_BLOCKING_ENTRANCE);
	FlagSet(FLAG_HIDE_MOSSDEEP_CITY_TEAM_MAGMA);
	FlagSet(FLAG_HIDE_PETALBURG_GYM_WALLYS_DAD);
	FlagSet(FLAG_HIDE_SOOTOPOLIS_CITY_ARCHIE);
	FlagSet(FLAG_HIDE_SOOTOPOLIS_CITY_MAXIE);
	FlagSet(FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_ARCHIE);
	FlagSet(FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAXIE);
	FlagSet(FLAG_HIDE_PETALBURG_CITY_WALLYS_DAD);
	FlagSet(FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAGMA_GRUNTS);
	FlagSet(FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER);
	FlagSet(FLAG_HIDE_GRANITE_CAVE_STEVEN);
	FlagSet(FLAG_HIDE_ROUTE_128_STEVEN);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_GABBY_AND_TY);
	FlagSet(FLAG_HIDE_BATTLE_FRONTIER_RECEPTION_GATE_SCOTT);
	FlagSet(FLAG_HIDE_ROUTE_110_BIRCH);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CHIKORITA);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_CAPTAIN_STERN);
	FlagSet(FLAG_HIDE_ROUTE_111_ROCK_SMASH_TIP_GUY);
	FlagSet(FLAG_HIDE_RUSTBORO_CITY_SCIENTIST);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_HARBOR_AQUA_GRUNT);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_HARBOR_ARCHIE);
	FlagSet(FLAG_HIDE_JAGGED_PASS_MAGMA_GUARD);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_HARBOR_SUBMARINE_SHADOW);
	FlagSet(FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON_ASLEEP);
	FlagSet(FLAG_HIDE_ROUTE_119_RIVAL);
	FlagSet(FLAG_HIDE_LILYCOVE_CITY_AQUA_GRUNTS);
	FlagSet(FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON);
	FlagSet(FLAG_HIDE_SOOTOPOLIS_CITY_RESIDENTS);
	FlagSet(FLAG_HIDE_SKY_PILLAR_WALLACE);
	FlagSet(FLAG_HIDE_MT_PYRE_SUMMIT_MAXIE);
	FlagSet(FLAG_HIDE_MAGMA_HIDEOUT_GRUNTS);
	FlagSet(FLAG_HIDE_VICTORY_ROAD_ENTRANCE_WALLY);
	FlagSet(FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE);
	FlagSet(FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_TEAM_MAGMA);
	FlagSet(FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_STEVEN);
	FlagSet(FLAG_HIDE_PETALBURG_GYM_WALLY);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_STERNS_SHIPYARD_MR_BRINEY);
	FlagSet(FLAG_HIDE_LANETTES_HOUSE_LANETTE);
	FlagSet(FLAG_HIDE_TRICK_HOUSE_ENTRANCE_MAN);
	FlagSet(FLAG_HIDE_DESERT_UNDERPASS_FOSSIL);
	FlagSet(FLAG_HIDE_ROUTE_111_PLAYER_DESCENT);
	FlagSet(FLAG_HIDE_ROUTE_111_DESERT_FOSSIL);
	FlagSet(FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT);
	FlagSet(FLAG_HIDE_RUSTURF_TUNNEL_BRINEY);
	FlagSet(FLAG_HIDE_RUSTURF_TUNNEL_PEEKO);
	FlagSet(FLAG_HIDE_BRINEYS_HOUSE_PEEKO);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_TEAM_AQUA);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_AQUA_GRUNTS);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_1);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_2);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_ARCHIE);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_CAPTAIN_STERN);
	FlagSet(FLAG_HIDE_BATTLE_TOWER_OPPONENT);
	FlagSet(FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_RIVAL);
	FlagSet(FLAG_HIDE_ROUTE_119_TEAM_AQUA);
	FlagSet(FLAG_HIDE_ROUTE_116_MR_BRINEY);
	FlagSet(FLAG_HIDE_WEATHER_INSTITUTE_2F_WORKERS);
	FlagSet(FLAG_HIDE_ROUTE_116_WANDAS_BOYFRIEND);
	FlagSet(FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_2);
	FlagSet(FLAG_HIDE_ROUTE_101_BIRCH);
	FlagSet(FLAG_HIDE_ROUTE_103_BIRCH);
	FlagSet(FLAG_HIDE_ROUTE_110_TEAM_AQUA);
	FlagSet(FLAG_HIDE_ROUTE_118_GABBY_AND_TY_2);
	FlagSet(FLAG_HIDE_ROUTE_120_GABBY_AND_TY_2);
	FlagSet(FLAG_HIDE_ROUTE_111_GABBY_AND_TY_2);
	FlagSet(FLAG_HIDE_ROUTE_118_GABBY_AND_TY_3);
	FlagSet(FLAG_HIDE_ROUTE_104_WHITE_HERB_FLORIST);
	FlagSet(FLAG_HIDE_LILYCOVE_HARBOR_FERRY_SAILOR);
	FlagSet(FLAG_HIDE_SOUTHERN_ISLAND_EON_STONE);
	FlagSet(FLAG_HIDE_SOUTHERN_ISLAND_UNCHOSEN_EON_DUO_MON);
	FlagSet(FLAG_HIDE_MAUVILLE_GYM_WATTSON);
	FlagSet(FLAG_HIDE_ROUTE_121_TEAM_AQUA_GRUNTS);
	FlagSet(FLAG_HIDE_MT_PYRE_SUMMIT_TEAM_AQUA);
	FlagSet(FLAG_HIDE_BATTLE_TOWER_REPORTER);
	FlagSet(FLAG_HIDE_ROUTE_110_RIVAL);
	FlagSet(FLAG_HIDE_CHAMPIONS_ROOM_RIVAL);
	FlagSet(FLAG_HIDE_CHAMPIONS_ROOM_BIRCH);
	FlagSet(FLAG_HIDE_ROUTE_110_RIVAL_ON_BIKE);
	FlagSet(FLAG_HIDE_AQUA_HIDEOUT_GRUNTS);
	FlagSet(FLAG_HIDE_MT_CHIMNEY_TEAM_AQUA);
	FlagSet(FLAG_HIDE_MT_CHIMNEY_TEAM_MAGMA);
	FlagSet(FLAG_HIDE_LAVARIDGE_TOWN_RIVAL);
	FlagSet(FLAG_HIDE_LAVARIDGE_TOWN_RIVAL_ON_BIKE);
	FlagSet(FLAG_HIDE_RUSTURF_TUNNEL_ROCK_2);
	FlagSet(FLAG_HIDE_MOSSDEEP_CITY_HOUSE_2_WINGULL);
	FlagSet(FLAG_HIDE_METEOR_FALLS_TEAM_AQUA);
	FlagSet(FLAG_HIDE_METEOR_FALLS_TEAM_MAGMA);
	FlagSet(FLAG_HIDE_SEAFLOOR_CAVERN_ENTRANCE_AQUA_GRUNT);
	FlagSet(FLAG_HIDE_METEOR_FALLS_1F_1R_COZMO);
	FlagSet(FLAG_HIDE_AQUA_HIDEOUT_B2F_SUBMARINE_SHADOW);
	FlagSet(FLAG_HIDE_ROUTE_128_ARCHIE);
	FlagSet(FLAG_HIDE_ROUTE_128_MAXIE);
	FlagSet(FLAG_HIDE_SEAFLOOR_CAVERN_AQUA_GRUNTS);
	FlagSet(FLAG_HIDE_RUSTBORO_CITY_DEVON_CORP_3F_EMPLOYEE);
	FlagSet(FLAG_HIDE_ROUTE_111_SECRET_POWER_MAN);
	FlagSet(FLAG_HIDE_LILYCOVE_DEPARTMENT_STORE_ROOFTOP_SALE_WOMAN);
	FlagSet(FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_FAMILIAR_AQUA_GRUNT);
	FlagSet(FLAG_HIDE_ROUTE_118_STEVEN);
	FlagSet(FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_STEVEN);
	FlagSet(FLAG_HIDE_FORTREE_CITY_KECLEON);
	FlagSet(FLAG_HIDE_ROUTE_120_KECLEON_BRIDGE);
	FlagSet(FLAG_HIDE_LILYCOVE_CITY_RIVAL);
	FlagSet(FLAG_HIDE_ROUTE_120_STEVEN);
	FlagSet(FLAG_HIDE_SOOTOPOLIS_CITY_STEVEN);
	FlagSet(FLAG_HIDE_AQUA_HIDEOUT_B1F_ELECTRODE_1);
	FlagSet(FLAG_HIDE_AQUA_HIDEOUT_B1F_ELECTRODE_2);
	FlagSet(FLAG_HIDE_OLDALE_TOWN_RIVAL);
	FlagSet(FLAG_HIDE_ROUTE_120_KECLEON_BRIDGE_SHADOW);
	FlagSet(FLAG_HIDE_ROUTE_120_KECLEON_1);
	FlagSet(FLAG_HIDE_RUSTURF_TUNNEL_WANDA);
	FlagSet(FLAG_HIDE_ROUTE_120_KECLEON_2);
	FlagSet(FLAG_HIDE_ROUTE_120_KECLEON_3);
	FlagSet(FLAG_HIDE_ROUTE_120_KECLEON_4);
	FlagSet(FLAG_HIDE_ROUTE_120_KECLEON_5);
	FlagSet(FLAG_HIDE_ROUTE_119_KECLEON_1);
	FlagSet(FLAG_HIDE_ROUTE_119_KECLEON_2);
	FlagSet(FLAG_HIDE_ROUTE_101_BOY);
	FlagSet(FLAG_HIDE_WEATHER_INSTITUTE_2F_AQUA_GRUNT_M);
	FlagSet(FLAG_HIDE_LILYCOVE_POKEMON_CENTER_CONTEST_LADY_MON);
	FlagSet(FLAG_HIDE_PETALBURG_CITY_SCOTT);
	FlagSet(FLAG_HIDE_SOOTOPOLIS_CITY_RAYQUAZA);
	FlagSet(FLAG_HIDE_SOOTOPOLIS_CITY_KYOGRE);
	FlagSet(FLAG_HIDE_SOOTOPOLIS_CITY_GROUDON);
	FlagSet(FLAG_HIDE_RUSTBORO_CITY_POKEMON_SCHOOL_SCOTT);

	// Gym Flags
	FlagSet(FLAG_DEFEATED_RUSTBORO_GYM);
	FlagSet(FLAG_DEFEATED_DEWFORD_GYM);
	FlagSet(FLAG_DEFEATED_MAUVILLE_GYM);
	FlagSet(FLAG_DEFEATED_LAVARIDGE_GYM);
	FlagSet(FLAG_DEFEATED_PETALBURG_GYM);
	FlagSet(FLAG_DEFEATED_FORTREE_GYM);
	FlagSet(FLAG_DEFEATED_MOSSDEEP_GYM);
	FlagSet(FLAG_DEFEATED_SOOTOPOLIS_GYM);

	// System Flags
	FlagSet(FLAG_SYS_POKEMON_GET);
	FlagSet(FLAG_SYS_POKEDEX_GET);
	FlagSet(FLAG_SYS_POKENAV_GET);
	FlagSet(FLAG_SYS_GAME_CLEAR);
	FlagSet(FLAG_BADGE01_GET);
	FlagSet(FLAG_BADGE02_GET);
	FlagSet(FLAG_BADGE03_GET);
	FlagSet(FLAG_BADGE04_GET);
	FlagSet(FLAG_BADGE05_GET);
	FlagSet(FLAG_BADGE06_GET);
	FlagSet(FLAG_BADGE07_GET);
	FlagSet(FLAG_BADGE08_GET);
	FlagSet(FLAG_BADGE08_GET);

	// Fly Flags
	FlagSet(FLAG_VISITED_LITTLEROOT_TOWN);
	FlagSet(FLAG_VISITED_OLDALE_TOWN);
	FlagSet(FLAG_VISITED_DEWFORD_TOWN);
	FlagSet(FLAG_VISITED_LAVARIDGE_TOWN);
	FlagSet(FLAG_VISITED_FALLARBOR_TOWN);
	FlagSet(FLAG_VISITED_VERDANTURF_TOWN);
	FlagSet(FLAG_VISITED_PACIFIDLOG_TOWN);
	FlagSet(FLAG_VISITED_PETALBURG_CITY);
	FlagSet(FLAG_VISITED_SLATEPORT_CITY);
	FlagSet(FLAG_VISITED_MAUVILLE_CITY);
	FlagSet(FLAG_VISITED_RUSTBORO_CITY);
	FlagSet(FLAG_VISITED_FORTREE_CITY);
	FlagSet(FLAG_VISITED_LILYCOVE_CITY);
	FlagSet(FLAG_VISITED_MOSSDEEP_CITY);
	FlagSet(FLAG_VISITED_SOOTOPOLIS_CITY);
	FlagSet(FLAG_VISITED_EVER_GRANDE_CITY);

	// More system flags
	FlagSet(FLAG_IS_CHAMPION);
	FlagSet(FLAG_SYS_TV_HOME);
	FlagSet(FLAG_SYS_TV_WATCH);
	FlagSet(FLAG_SYS_TV_START);
	FlagSet(FLAG_SYS_CLOCK_SET);
	FlagSet(FLAG_SYS_NATIONAL_DEX);
	FlagSet(FLAG_SYS_RIBBON_GET);
	
	// Landmarks
	FlagSet(FLAG_LANDMARK_MR_BRINEY_HOUSE);
	FlagSet(FLAG_LANDMARK_WINSTRATE_FAMILY);
	FlagSet(FLAG_LANDMARK_GLASS_WORKSHOP);
	FlagSet(FLAG_LANDMARK_LANETTES_HOUSE);
	FlagSet(FLAG_LANDMARK_SEAFLOOR_CAVERN);
	FlagSet(FLAG_LANDMARK_BATTLE_FRONTIER);
	FlagSet(FLAG_LANDMARK_FIERY_PATH);
	FlagSet(FLAG_LANDMARK_POKEMON_LEAGUE);
	FlagSet(FLAG_LANDMARK_TUNNELERS_REST_HOUSE);
	FlagSet(FLAG_LANDMARK_BERRY_MASTERS_HOUSE);
	FlagSet(FLAG_LANDMARK_SKY_PILLAR);

	// Even more system flags
	FlagSet(FLAG_SYS_FRONTIER_PASS);
	FlagSet(FLAG_SYS_SHOAL_ITEM);
	FlagSet(FLAG_SYS_B_DASH);

	// Leftover Flags
	FlagSet(FLAG_ARRIVED_ON_FARAWAY_ISLAND);
	FlagSet(FLAG_LANDMARK_TRAINER_HILL);

	// Tera Orb
	FlagSet(FLAG_TERA_ORB_CHARGED);
	FlagSet(FLAG_TERA_ORB_NO_COST);

	// (New!) Battle Frontier Generator Flags
	FlagSet(FLAG_BATTLE_FRONTIER_GENERATOR);
	FlagSet(FLAG_BATTLE_FRONTIER_ALLOW_MEGA);
	FlagSet(FLAG_BATTLE_FRONTIER_ALLOW_ZMOVE);
	FlagSet(FLAG_BATTLE_FRONTIER_ALLOW_TERA);
	FlagSet(FLAG_BATTLE_FRONTIER_ALLOW_GMAX);
	FlagSet(FLAG_BATTLE_FRONTIER_GENERATOR);
}

static void SetQuickStartVars(void)
{
    // Location States
	VarSet(VAR_BIRCH_STATE, 4);
	VarSet(VAR_LITTLEROOT_TOWN_STATE, 4);
	VarSet(VAR_OLDALE_TOWN_STATE, 1);
	VarSet(VAR_LAVARIDGE_TOWN_STATE, 2);
	VarSet(VAR_PETALBURG_CITY_STATE, 5);
	VarSet(VAR_SLATEPORT_CITY_STATE, 2);
	VarSet(VAR_RUSTBORO_CITY_STATE, 8);
	VarSet(VAR_MOSSDEEP_CITY_STATE, 3);
	VarSet(VAR_SOOTOPOLIS_CITY_STATE, 6);
	VarSet(VAR_ROUTE101_STATE, 3);
	VarSet(VAR_ROUTE104_STATE, 2);
	VarSet(VAR_ROUTE110_STATE, 1);
	VarSet(VAR_ROUTE116_STATE, 2);
	VarSet(VAR_ROUTE118_STATE, 1);
	VarSet(VAR_ROUTE119_STATE, 1);
	VarSet(VAR_ROUTE121_STATE, 1);
	VarSet(VAR_ROUTE128_STATE, 2);
	VarSet(VAR_LITTLEROOT_HOUSES_STATE_MAY, 5);
	VarSet(VAR_BIRCH_LAB_STATE, 5);
	VarSet(VAR_PETALBURG_GYM_STATE, 7);
	VarSet(VAR_SECRET_BASE_INITIALIZED, 1);
	VarSet(VAR_LITTLEROOT_HOUSES_STATE_BRENDAN, 5);
	VarSet(VAR_LITTLEROOT_RIVAL_STATE, 4);
	VarSet(VAR_BOARD_BRINEY_BOAT_STATE, 2);
	VarSet(VAR_DEVON_CORP_3F_STATE, 1);
	VarSet(VAR_BRINEY_HOUSE_STATE, 1);
	VarSet(VAR_LITTLEROOT_INTRO_STATE, 7);
	VarSet(VAR_LILYCOVE_FAN_CLUB_STATE, 1);
	VarSet(VAR_PETALBURG_WOODS_STATE, 1);
	VarSet(VAR_RUSTURF_TUNNEL_STATE, 6);
	VarSet(VAR_MOSSDEEP_SPACE_CENTER_STAIR_GUARD_STATE, 2);
	VarSet(VAR_MOSSDEEP_SPACE_CENTER_STATE, 3);
	VarSet(VAR_SLATEPORT_HARBOR_STATE, 2);
	VarSet(VAR_SEAFLOOR_CAVERN_STATE, 1);
	VarSet(VAR_WEATHER_INSTITUTE_STATE, 2);
	VarSet(VAR_SS_TIDAL_STATE, 8);
	VarSet(VAR_MT_PYRE_STATE, 2);
	VarSet(VAR_NEW_MAUVILLE_STATE, 2);
	VarSet(VAR_GLASS_WORKSHOP_STATE, 2);
	VarSet(VAR_METEOR_FALLS_STATE, 2);
	VarSet(VAR_VICTORY_ROAD_1F_STATE, 2);
	VarSet(VAR_STEVENS_HOUSE_STATE, 2);
	VarSet(VAR_OLDALE_RIVAL_STATE, 2);
	VarSet(VAR_OLDALE_RIVAL_STATE, 2);
	VarSet(VAR_JAGGED_PASS_STATE, 2);
	VarSet(VAR_SCOTT_PETALBURG_ENCOUNTER, 1);
	VarSet(VAR_SKY_PILLAR_STATE, 3);
	VarSet(VAR_FOSSIL_MANIAC_STATE, 1);
	VarSet(VAR_CABLE_CLUB_TUTORIAL_STATE, 2);
	VarSet(VAR_FRONTIER_BATTLE_MODE, 1);
	VarSet(VAR_HAS_ENTERED_BATTLE_FRONTIER, 1);
	VarSet(VAR_SCOTT_STATE, 6);
	VarSet(VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE, 3);
	VarSet(VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 3);
	VarSet(VAR_SS_TIDAL_SCOTT_STATE, 1);
	VarSet(VAR_ROAMER_POKEMON, 1);
	VarSet(VAR_SKY_PILLAR_RAYQUAZA_CRY_DONE, 1);
	VarSet(VAR_SOOTOPOLIS_WALLACE_STATE, 1);
	VarSet(VAR_REGISTER_BIRCH_STATE, 2);

	// Step Counters
	VarSet(VAR_WALLY_CALL_STEP_COUNTER, 250);
	VarSet(VAR_SCOTT_FORTREE_CALL_STEP_COUNTER, 10);
	VarSet(VAR_ROXANNE_CALL_STEP_COUNTER, 250);
	VarSet(VAR_SCOTT_BF_CALL_STEP_COUNTER, 10);
	VarSet(VAR_RIVAL_RAYQUAZA_CALL_STEP_COUNTER, 250);

    // (New!) Set Frontier Set Generation Method
    VarSet(VAR_FRONTIER_METHOD, BFG_TEAM_GENERATOR_FILTERED_RANKING);
}

static void GiveQuickStartItems(void)
{
    // Battle Mechanic Key Items
    AddBagItem(ITEM_MEGA_RING, 1);
    AddBagItem(ITEM_Z_POWER_RING, 1);
    AddBagItem(ITEM_DYNAMAX_BAND, 1);

    // Form-changing Key Items
    AddBagItem(ITEM_ROTOM_CATALOG, 1);
    AddBagItem(ITEM_GRACIDEA, 1);
    AddBagItem(ITEM_REVEAL_GLASS, 1);
    AddBagItem(ITEM_DNA_SPLICERS, 1);
    AddBagItem(ITEM_ZYGARDE_CUBE, 1);
    AddBagItem(ITEM_PRISON_BOTTLE, 1);
    AddBagItem(ITEM_N_SOLARIZER, 1);
    AddBagItem(ITEM_N_LUNARIZER, 1);
    AddBagItem(ITEM_REINS_OF_UNITY, 1);

    // Story / Other Key Items
    AddBagItem(ITEM_MACH_BIKE, 1);
    AddBagItem(ITEM_OLD_ROD, 1);
    AddBagItem(ITEM_GOOD_ROD, 1);
    AddBagItem(ITEM_SUPER_ROD, 1);
    AddBagItem(ITEM_DOWSING_MACHINE, 1);
    AddBagItem(ITEM_SOOT_SACK, 1);
    AddBagItem(ITEM_METEORITE, 1);
    AddBagItem(ITEM_GO_GOGGLES, 1);
    AddBagItem(ITEM_DEVON_SCOPE, 1);
    AddBagItem(ITEM_MAGMA_EMBLEM, 1);
    AddBagItem(ITEM_SS_TICKET, 1);
    AddBagItem(ITEM_COIN_CASE, 1);
    
    // If escape rope is a key item
    #if I_KEY_ESCAPE_ROPE >= GEN_9
    AddBagItem(I_KEY_ESCAPE_ROPE, 1);
    #endif

    // Other items may be added later :)
}

static void UpdatePokedex(struct Pokemon * mon) {
	// Update Pokedex flags	
	u16 species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    u32 personality = GetMonData(mon, MON_DATA_PERSONALITY, NULL);
    species = SpeciesToNationalPokedexNum(species);

    GetSetPokedexFlag(species, FLAG_SET_SEEN);
    HandleSetPokedexFlag(species, FLAG_SET_CAUGHT, personality);
}

static void GiveVolcarona(void) {

	// Flame Body / Battle Lead
	struct Pokemon volcarona;

	CreateMonWithNature(
		&volcarona, 
		SPECIES_VOLCARONA, 
		100, 
		31, 
		NATURE_MODEST
	);

	// Moves
	u16 moves[] = {MOVE_FIERY_DANCE, MOVE_GIGA_DRAIN, MOVE_BUG_BUZZ, MOVE_QUIVER_DANCE};
	SetMonData(&volcarona, MON_DATA_MOVE1, &moves[0]);
	SetMonData(&volcarona, MON_DATA_MOVE2, &moves[1]);
	SetMonData(&volcarona, MON_DATA_MOVE3, &moves[2]);
	SetMonData(&volcarona, MON_DATA_MOVE4, &moves[3]);

	// Restore PP to full
	MonRestorePP(&volcarona);

	// Ability
	u16 ability = 0; // Flame Body
	SetMonData(&volcarona, MON_DATA_ABILITY_NUM, &ability);

	// Item
	u16 item = ITEM_LEFTOVERS;
	SetMonData(&volcarona, MON_DATA_HELD_ITEM, &item);

	// Tera Type
	u16 tera = TYPE_GRASS;
	SetMonData(&volcarona, MON_DATA_TERA_TYPE, &tera);

	// EVs
	u8 evMin = 4;
	u8 evMax = 252;
	SetMonData(&volcarona, MON_DATA_HP_EV, &evMax);
	SetMonData(&volcarona, MON_DATA_SPATK_EV, &evMax);
	SetMonData(&volcarona, MON_DATA_DEF_EV, &evMin);

    GiveMonToPlayer(&volcarona);
	UpdatePokedex(&volcarona);
}

static void GiveSmeargle(void) {

	// HM Slave Supporter
	struct Pokemon smeargle;

    CreateMonWithNature(
        &smeargle, 
        SPECIES_SMEARGLE, 
        100, 
        31, 
        NATURE_SASSY
    );

	// Moves
	u16 moves[] = {MOVE_WATERFALL, MOVE_DIVE, MOVE_SURF, MOVE_FLY};
	SetMonData(&smeargle, MON_DATA_MOVE1, &moves[0]);
	SetMonData(&smeargle, MON_DATA_MOVE2, &moves[1]);
	SetMonData(&smeargle, MON_DATA_MOVE3, &moves[2]);
	SetMonData(&smeargle, MON_DATA_MOVE4, &moves[3]);

	// Restore PP to full
	MonRestorePP(&smeargle);

	// Ability
	u16 ability = 2; // Moody
	SetMonData(&smeargle, MON_DATA_ABILITY_NUM, &ability);

	// Item
	u16 item = ITEM_LEFTOVERS;
	SetMonData(&smeargle, MON_DATA_HELD_ITEM, &item); 

	// Tera Type
	u16 tera = TYPE_WATER;
	SetMonData(&smeargle, MON_DATA_TERA_TYPE, &tera);

	// EVs
	u8 evMin = 4;
	u8 evMax = 252;
	SetMonData(&smeargle, MON_DATA_HP_EV, &evMax);
	SetMonData(&smeargle, MON_DATA_DEF_EV, &evMax);
	SetMonData(&smeargle, MON_DATA_SPDEF_EV, &evMin);

    GiveMonToPlayer(&smeargle);
	UpdatePokedex(&smeargle);
}
#endif
